In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-05-03-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

C:\Users\Doug Smith\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,Ensemble,2021-05-03,1 wk ahead inc case,2021-05-08,Alabama,Alabama,01,2384,1041,1775,2957,4642
1,JHU-IDD,2021-05-03,1 wk ahead inc case,2021-05-08,Alabama,Alabama,01,2092,3,102,1693,19874
2,JHU-UNC-Google,2021-05-03,1 wk ahead inc case,2021-05-08,Alabama,Alabama,01,2956,992,2490,3953,5126
3,IEM,2021-05-03,1 wk ahead inc case,2021-05-08,Alabama,Alabama,01,2752,1422,2229,3347,4718
4,UGA-CEID,2021-05-03,1 wk ahead inc case,2021-05-08,Alabama,Alabama,01,2220,65,1470,3042,4291

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,Ensemble,2021-05-03,1 wk ahead inc case,2021-05-08,Alabama,Alabama,01,2384,1041,1775,2957,4642
1,JHU-IDD,2021-05-03,1 wk ahead inc case,2021-05-08,Alabama,Alabama,01,2092,3,102,1693,19874
2,JHU-UNC-Google,2021-05-03,1 wk ahead inc case,2021-05-08,Alabama,Alabama,01,2956,992,2490,3953,5126
3,IEM,2021-05-03,1 wk ahead inc case,2021-05-08,Alabama,Alabama,01,2752,1422,2229,3347,4718
4,UGA-CEID,2021-05-03,1 wk ahead inc case,2021-05-08,Alabama,Alabama,01,2220,65,1470,3042,4291

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
21,UVA,2021-05-03,1 wk ahead inc case,2021-05-08,Autauga,Alabama,01001,94,0,59,129,194
22,LNQ,2021-05-03,1 wk ahead inc case,2021-05-08,Autauga,Alabama,01001,32,2,16,59,137
23,JHU-APL,2021-05-03,1 wk ahead inc case,2021-05-08,Autauga,Alabama,01001,80,46,64,100,156
24,Columbia,2021-05-03,1 wk ahead inc case,2021-05-08,Autauga,Alabama,01001,54,21,42,71,108
25,FRBSF-Wilson,2021-05-03,1 wk ahead inc case,2021-05-08,Autauga,Alabama,01001,51,35,46,58,74
...,...,...,...,...,...,...,...,...,...,...,...,...
143259,PandemicCentral,2021-05-03,4 wk ahead inc case,2021-05-29,Weston,Wyoming,56045,5,0,1,8,13
143260,LANL,2021-05-03,4 wk ahead inc case,2021-05-29,Weston,Wyoming,56045,3,0,2,5,10
143261,Facebook,2021-05-03,4 wk ahead inc case,2021-05-29,Weston,Wyoming,56045,3,0,0,9,21
143262,Ensemble,2021-05-03,4 wk ahead inc case,2021-05-29,Weston,Wyoming,56045,2,0,0,5,14
143263,Columbia,2021-05-03,4 wk ahead inc case,2021-05-29,Weston,Wyoming,56045,0,0,0,0,14

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)