In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-05-31-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

C:\Users\Doug Smith\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,MIT-ISOLAT,2021-05-31,1 wk ahead inc case,2021-06-05,Alabama,Alabama,01,2931,1082,2294,3567,4779
1,Ensemble,2021-05-31,1 wk ahead inc case,2021-06-05,Alabama,Alabama,01,1602,459,1103,2272,3538
2,Masaryk University,2021-05-31,1 wk ahead inc case,2021-06-05,Alabama,Alabama,01,442,37,272,678,1394
3,LANL,2021-05-31,1 wk ahead inc case,2021-06-05,Alabama,Alabama,01,1406,55,569,2868,8163
4,MIT-ORC,2021-05-31,1 wk ahead inc case,2021-06-05,Alabama,Alabama,01,319,0,0,720,1484

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,MIT-ISOLAT,2021-05-31,1 wk ahead inc case,2021-06-05,Alabama,Alabama,01,2931,1082,2294,3567,4779
1,Ensemble,2021-05-31,1 wk ahead inc case,2021-06-05,Alabama,Alabama,01,1602,459,1103,2272,3538
2,Masaryk University,2021-05-31,1 wk ahead inc case,2021-06-05,Alabama,Alabama,01,442,37,272,678,1394
3,LANL,2021-05-31,1 wk ahead inc case,2021-06-05,Alabama,Alabama,01,1406,55,569,2868,8163
4,MIT-ORC,2021-05-31,1 wk ahead inc case,2021-06-05,Alabama,Alabama,01,319,0,0,720,1484

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
24,Ensemble,2021-05-31,1 wk ahead inc case,2021-06-05,Autauga,Alabama,01001,71,0,35,86,165
25,FRBSF-Wilson,2021-05-31,1 wk ahead inc case,2021-06-05,Autauga,Alabama,01001,71,37,59,86,134
26,UGA-CEID,2021-05-31,1 wk ahead inc case,2021-06-05,Autauga,Alabama,01001,35,0,0,69,195
27,JHU-UNC-Google,2021-05-31,1 wk ahead inc case,2021-06-05,Autauga,Alabama,01001,68,0,35,125,196
28,UVA,2021-05-31,1 wk ahead inc case,2021-06-05,Autauga,Alabama,01001,100,0,45,156,261
...,...,...,...,...,...,...,...,...,...,...,...,...
137459,Facebook,2021-05-31,4 wk ahead inc case,2021-06-26,Weston,Wyoming,56045,1,0,0,5,12
137460,Columbia,2021-05-31,4 wk ahead inc case,2021-06-26,Weston,Wyoming,56045,0,0,0,0,14
137461,LANL,2021-05-31,4 wk ahead inc case,2021-06-26,Weston,Wyoming,56045,1,0,0,2,5
137462,UVA,2021-05-31,4 wk ahead inc case,2021-06-26,Weston,Wyoming,56045,2,1,2,3,3
137463,JHU-UNC-Google,2021-05-31,4 wk ahead inc case,2021-06-26,Weston,Wyoming,56045,0,0,0,7,29

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)