In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-02-22-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,JHU-APL,2021-02-22,1 wk ahead inc case,2021-02-27,Alabama,Alabama,01,3360,2214,2890,3894,5040
1,IEM,2021-02-22,1 wk ahead inc case,2021-02-27,Alabama,Alabama,01,4530,2601,3780,5320,7095
2,SignatureScience,2021-02-22,1 wk ahead inc case,2021-02-27,Alabama,Alabama,01,5829,671,4054,7604,10988
3,USC,2021-02-22,1 wk ahead inc case,2021-02-27,Alabama,Alabama,01,5478,4237,5079,6370,7474
4,Ensemble,2021-02-22,1 wk ahead inc case,2021-02-27,Alabama,Alabama,01,5245,2475,4347,6417,8292

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,JHU-APL,2021-02-22,1 wk ahead inc case,2021-02-27,Alabama,Alabama,01,3360,2214,2890,3894,5040
1,IEM,2021-02-22,1 wk ahead inc case,2021-02-27,Alabama,Alabama,01,4530,2601,3780,5320,7095
2,SignatureScience,2021-02-22,1 wk ahead inc case,2021-02-27,Alabama,Alabama,01,5829,671,4054,7604,10988
3,USC,2021-02-22,1 wk ahead inc case,2021-02-27,Alabama,Alabama,01,5478,4237,5079,6370,7474
4,Ensemble,2021-02-22,1 wk ahead inc case,2021-02-27,Alabama,Alabama,01,5245,2475,4347,6417,8292

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
25,UGA-CEID,2021-02-22,1 wk ahead inc case,2021-02-27,Autauga,Alabama,01001,97,0,55,132,264
26,JHU-UNC-Google,2021-02-22,1 wk ahead inc case,2021-02-27,Autauga,Alabama,01001,125,54,91,152,226
27,JHU-APL,2021-02-22,1 wk ahead inc case,2021-02-27,Autauga,Alabama,01001,53,34,45,62,81
28,LANL,2021-02-22,1 wk ahead inc case,2021-02-27,Autauga,Alabama,01001,71,27,47,108,216
29,UpstateSU,2021-02-22,1 wk ahead inc case,2021-02-27,Autauga,Alabama,01001,127,120,125,131,134
...,...,...,...,...,...,...,...,...,...,...,...,...
164059,Columbia,2021-02-22,4 wk ahead inc case,2021-03-20,Weston,Wyoming,56045,0,0,0,0,14
164060,UGA-CEID,2021-02-22,4 wk ahead inc case,2021-03-20,Weston,Wyoming,56045,3,0,0,7,14
164061,ISU,2021-02-22,4 wk ahead inc case,2021-03-20,Weston,Wyoming,56045,5,1,4,7,11
164062,LNQ,2021-02-22,4 wk ahead inc case,2021-03-20,Weston,Wyoming,56045,1,0,0,6,45
164063,OneQuietNight,2021-02-22,4 wk ahead inc case,2021-03-20,Weston,Wyoming,56045,16,0,3,28,53

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)