In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-12-06-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,BPagano,2021-12-06,1 wk ahead inc case,2021-12-11,Alabama,Alabama,01,2315,786,1777,2830,3821
1,MIT-ISOLAT,2021-12-06,1 wk ahead inc case,2021-12-11,Alabama,Alabama,01,2,0,1,4,5
2,Microsoft,2021-12-06,1 wk ahead inc case,2021-12-11,Alabama,Alabama,01,3760,3079,3545,3832,4405
3,UVA,2021-12-06,1 wk ahead inc case,2021-12-11,Alabama,Alabama,01,3103,0,1771,4434,6972
4,JHU-APL,2021-12-06,1 wk ahead inc case,2021-12-11,Alabama,Alabama,01,2170,1361,1834,2569,3448

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,BPagano,2021-12-06,1 wk ahead inc case,2021-12-11,Alabama,Alabama,01,2315,786,1777,2830,3821
1,MIT-ISOLAT,2021-12-06,1 wk ahead inc case,2021-12-11,Alabama,Alabama,01,2,0,1,4,5
2,Microsoft,2021-12-06,1 wk ahead inc case,2021-12-11,Alabama,Alabama,01,3760,3079,3545,3832,4405
3,UVA,2021-12-06,1 wk ahead inc case,2021-12-11,Alabama,Alabama,01,3103,0,1771,4434,6972
4,JHU-APL,2021-12-06,1 wk ahead inc case,2021-12-11,Alabama,Alabama,01,2170,1361,1834,2569,3448

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
16,Columbia,2021-12-06,1 wk ahead inc case,2021-12-11,Autauga,Alabama,01001,32,2,17,53,98
17,FRBSF-Wilson,2021-12-06,1 wk ahead inc case,2021-12-11,Autauga,Alabama,01001,0,17,33,54,96
18,Ensemble,2021-12-06,1 wk ahead inc case,2021-12-11,Autauga,Alabama,01001,32,2,18,49,91
19,JHU-APL,2021-12-06,1 wk ahead inc case,2021-12-11,Autauga,Alabama,01001,21,13,18,25,33
20,CUBoulder,2021-12-06,1 wk ahead inc case,2021-12-11,Autauga,Alabama,01001,28,4,18,41,89
...,...,...,...,...,...,...,...,...,...,...,...,...
42499,Ensemble,2021-12-06,2 wk ahead inc case,2021-12-18,Weston,Wyoming,56045,7,0,1,12,36
42500,CUBoulder,2021-12-06,2 wk ahead inc case,2021-12-18,Weston,Wyoming,56045,5,0,3,9,20
42501,Facebook,2021-12-06,2 wk ahead inc case,2021-12-18,Weston,Wyoming,56045,15,0,0,35,73
42502,UVA,2021-12-06,2 wk ahead inc case,2021-12-18,Weston,Wyoming,56045,7,0,0,19,41
42503,Columbia,2021-12-06,2 wk ahead inc case,2021-12-18,Weston,Wyoming,56045,0,0,0,0,15

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)