In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-03-29-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,Covid19Sim,2021-03-29,1 wk ahead inc case,2021-04-03,Alabama,Alabama,01,3529,3057,3465,3600,3714
1,LNQ,2021-03-29,1 wk ahead inc case,2021-04-03,Alabama,Alabama,01,2923,818,2060,3647,7101
2,IEM,2021-03-29,1 wk ahead inc case,2021-04-03,Alabama,Alabama,01,2693,148,1199,4903,11195
3,UM,2021-03-29,1 wk ahead inc case,2021-04-03,Alabama,Alabama,01,7019,4105,5925,8093,9733
4,JHU-APL,2021-03-29,1 wk ahead inc case,2021-04-03,Alabama,Alabama,01,3137,2090,2695,3599,4486

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,Covid19Sim,2021-03-29,1 wk ahead inc case,2021-04-03,Alabama,Alabama,01,3529,3057,3465,3600,3714
1,LNQ,2021-03-29,1 wk ahead inc case,2021-04-03,Alabama,Alabama,01,2923,818,2060,3647,7101
2,IEM,2021-03-29,1 wk ahead inc case,2021-04-03,Alabama,Alabama,01,2693,148,1199,4903,11195
3,UM,2021-03-29,1 wk ahead inc case,2021-04-03,Alabama,Alabama,01,7019,4105,5925,8093,9733
4,JHU-APL,2021-03-29,1 wk ahead inc case,2021-04-03,Alabama,Alabama,01,3137,2090,2695,3599,4486

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
24,Facebook,2021-03-29,1 wk ahead inc case,2021-04-03,Autauga,Alabama,01001,46,0,29,64,97
25,JHU-IDD,2021-03-29,1 wk ahead inc case,2021-04-03,Autauga,Alabama,01001,43,0,4,41,260
26,UpstateSU,2021-03-29,1 wk ahead inc case,2021-04-03,Autauga,Alabama,01001,69,62,63,74,78
27,Columbia,2021-03-29,1 wk ahead inc case,2021-04-03,Autauga,Alabama,01001,25,5,15,32,56
28,Ensemble,2021-03-29,1 wk ahead inc case,2021-04-03,Autauga,Alabama,01001,50,5,28,64,100
...,...,...,...,...,...,...,...,...,...,...,...,...
158491,Facebook,2021-03-29,4 wk ahead inc case,2021-04-24,Weston,Wyoming,56045,4,0,0,11,23
158492,LNQ,2021-03-29,4 wk ahead inc case,2021-04-24,Weston,Wyoming,56045,1,0,0,6,45
158493,LANL,2021-03-29,4 wk ahead inc case,2021-04-24,Weston,Wyoming,56045,1,0,0,3,13
158494,ISU,2021-03-29,4 wk ahead inc case,2021-04-24,Weston,Wyoming,56045,4,1,3,5,8
158495,UGA-CEID,2021-03-29,4 wk ahead inc case,2021-04-24,Weston,Wyoming,56045,0,0,0,10,28

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)