In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-03-01-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,Covid19Sim,2021-03-01,1 wk ahead inc case,2021-03-06,Alabama,Alabama,01,5962,5945,5961,5962,5978
1,SignatureScience,2021-03-01,1 wk ahead inc case,2021-03-06,Alabama,Alabama,01,6764,1652,5005,8524,11877
2,Ensemble,2021-03-01,1 wk ahead inc case,2021-03-06,Alabama,Alabama,01,5227,2891,4166,6092,7635
3,BPagano,2021-03-01,1 wk ahead inc case,2021-03-06,Alabama,Alabama,01,3591,1419,2826,4321,5729
4,Columbia,2021-03-01,1 wk ahead inc case,2021-03-06,Alabama,Alabama,01,5227,4267,4773,5827,8495

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,Covid19Sim,2021-03-01,1 wk ahead inc case,2021-03-06,Alabama,Alabama,01,5962,5945,5961,5962,5978
1,SignatureScience,2021-03-01,1 wk ahead inc case,2021-03-06,Alabama,Alabama,01,6764,1652,5005,8524,11877
2,Ensemble,2021-03-01,1 wk ahead inc case,2021-03-06,Alabama,Alabama,01,5227,2891,4166,6092,7635
3,BPagano,2021-03-01,1 wk ahead inc case,2021-03-06,Alabama,Alabama,01,3591,1419,2826,4321,5729
4,Columbia,2021-03-01,1 wk ahead inc case,2021-03-06,Alabama,Alabama,01,5227,4267,4773,5827,8495

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
26,LANL,2021-03-01,1 wk ahead inc case,2021-03-06,Autauga,Alabama,01001,185,60,132,251,426
27,UpstateSU,2021-03-01,1 wk ahead inc case,2021-03-06,Autauga,Alabama,01001,127,110,121,131,143
28,Ensemble,2021-03-01,1 wk ahead inc case,2021-03-06,Autauga,Alabama,01001,108,26,64,140,244
29,UVA,2021-03-01,1 wk ahead inc case,2021-03-06,Autauga,Alabama,01001,68,0,16,120,217
30,JHU-UNC-Google,2021-03-01,1 wk ahead inc case,2021-03-06,Autauga,Alabama,01001,55,0,42,169,769
...,...,...,...,...,...,...,...,...,...,...,...,...
164347,UVA,2021-03-01,4 wk ahead inc case,2021-03-27,Weston,Wyoming,56045,0,0,0,2,3
164348,Facebook,2021-03-01,4 wk ahead inc case,2021-03-27,Weston,Wyoming,56045,3,0,0,9,21
164349,LNQ,2021-03-01,4 wk ahead inc case,2021-03-27,Weston,Wyoming,56045,0,0,0,6,41
164350,JHU-APL,2021-03-01,4 wk ahead inc case,2021-03-27,Weston,Wyoming,56045,6,2,4,9,16
164351,LANL,2021-03-01,4 wk ahead inc case,2021-03-27,Weston,Wyoming,56045,3,0,2,4,7

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)