In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-04-05-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,BPagano,2021-04-05,1 wk ahead inc case,2021-04-10,Alabama,Alabama,01,2671,1055,2102,3215,4262
1,IEM,2021-04-05,1 wk ahead inc case,2021-04-10,Alabama,Alabama,01,2450,689,1676,3343,5353
2,UM,2021-04-05,1 wk ahead inc case,2021-04-10,Alabama,Alabama,01,3620,107,2511,5109,8173
3,MIT-ORC,2021-04-05,1 wk ahead inc case,2021-04-10,Alabama,Alabama,01,1883,324,1346,2420,3442
4,LNQ,2021-04-05,1 wk ahead inc case,2021-04-10,Alabama,Alabama,01,2236,570,1697,2775,4750

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,BPagano,2021-04-05,1 wk ahead inc case,2021-04-10,Alabama,Alabama,01,2671,1055,2102,3215,4262
1,IEM,2021-04-05,1 wk ahead inc case,2021-04-10,Alabama,Alabama,01,2450,689,1676,3343,5353
2,UM,2021-04-05,1 wk ahead inc case,2021-04-10,Alabama,Alabama,01,3620,107,2511,5109,8173
3,MIT-ORC,2021-04-05,1 wk ahead inc case,2021-04-10,Alabama,Alabama,01,1883,324,1346,2420,3442
4,LNQ,2021-04-05,1 wk ahead inc case,2021-04-10,Alabama,Alabama,01,2236,570,1697,2775,4750

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
23,LNQ,2021-04-05,1 wk ahead inc case,2021-04-10,Autauga,Alabama,01001,38,2,21,62,137
24,Columbia,2021-04-05,1 wk ahead inc case,2021-04-10,Autauga,Alabama,01001,26,4,17,36,63
25,ISU,2021-04-05,1 wk ahead inc case,2021-04-10,Autauga,Alabama,01001,54,41,50,60,68
26,JHU-IDD,2021-04-05,1 wk ahead inc case,2021-04-10,Autauga,Alabama,01001,37,0,3,37,244
27,UpstateSU,2021-04-05,1 wk ahead inc case,2021-04-10,Autauga,Alabama,01001,55,50,53,57,59
...,...,...,...,...,...,...,...,...,...,...,...,...
158271,LNQ,2021-04-05,4 wk ahead inc case,2021-05-01,Weston,Wyoming,56045,0,0,0,6,42
158272,FRBSF-Wilson,2021-04-05,4 wk ahead inc case,2021-05-01,Weston,Wyoming,56045,0,0,0,1,2
158273,LANL,2021-04-05,4 wk ahead inc case,2021-05-01,Weston,Wyoming,56045,1,0,0,3,12
158274,UGA-CEID,2021-04-05,4 wk ahead inc case,2021-05-01,Weston,Wyoming,56045,2,0,0,11,29
158275,JHU-IDD,2021-04-05,4 wk ahead inc case,2021-05-01,Weston,Wyoming,56045,2,0,0,1,15

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)