In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-02-08-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,JHU-CSSE,2021-02-08,1 wk ahead inc case,2021-02-13,Alabama,Alabama,01,15011,10641,12189,17438,20196
1,ESG,2021-02-08,1 wk ahead inc case,2021-02-13,Alabama,Alabama,01,12739,7381,10896,14582,18098
2,Ensemble,2021-02-08,1 wk ahead inc case,2021-02-13,Alabama,Alabama,01,14020,9141,11334,14991,18899
3,ISU,2021-02-08,1 wk ahead inc case,2021-02-13,Alabama,Alabama,01,14627,14293,14505,14742,14953
4,LANL,2021-02-08,1 wk ahead inc case,2021-02-13,Alabama,Alabama,01,10038,4681,7859,12642,18928

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,JHU-CSSE,2021-02-08,1 wk ahead inc case,2021-02-13,Alabama,Alabama,01,15011,10641,12189,17438,20196
1,ESG,2021-02-08,1 wk ahead inc case,2021-02-13,Alabama,Alabama,01,12739,7381,10896,14582,18098
2,Ensemble,2021-02-08,1 wk ahead inc case,2021-02-13,Alabama,Alabama,01,14020,9141,11334,14991,18899
3,ISU,2021-02-08,1 wk ahead inc case,2021-02-13,Alabama,Alabama,01,14627,14293,14505,14742,14953
4,LANL,2021-02-08,1 wk ahead inc case,2021-02-13,Alabama,Alabama,01,10038,4681,7859,12642,18928

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
24,PandemicCentral,2021-02-08,1 wk ahead inc case,2021-02-13,Autauga,Alabama,01001,156,72,98,164,361
25,UCLA,2021-02-08,1 wk ahead inc case,2021-02-13,Autauga,Alabama,01001,225,0,0,0,0
26,JHU-UNC-Google,2021-02-08,1 wk ahead inc case,2021-02-13,Autauga,Alabama,01001,136,0,99,198,397
27,OneQuietNight,2021-02-08,1 wk ahead inc case,2021-02-13,Autauga,Alabama,01001,201,0,125,280,441
28,LANL,2021-02-08,1 wk ahead inc case,2021-02-13,Autauga,Alabama,01001,127,31,81,193,378
...,...,...,...,...,...,...,...,...,...,...,...,...
169863,Facebook,2021-02-08,4 wk ahead inc case,2021-03-06,Weston,Wyoming,56045,3,0,0,10,23
169864,LNQ,2021-02-08,4 wk ahead inc case,2021-03-06,Weston,Wyoming,56045,3,0,0,12,60
169865,PandemicCentral,2021-02-08,4 wk ahead inc case,2021-03-06,Weston,Wyoming,56045,14,0,3,23,47
169866,Columbia,2021-02-08,4 wk ahead inc case,2021-03-06,Weston,Wyoming,56045,0,0,0,0,14
169867,OneQuietNight,2021-02-08,4 wk ahead inc case,2021-03-06,Weston,Wyoming,56045,18,0,5,31,55

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)