In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-05-17-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

C:\Users\Doug Smith\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,BPagano,2021-05-17,1 wk ahead inc case,2021-05-22,Alabama,Alabama,01,2134,0,1348,2886,4333
1,JHU-IDD,2021-05-17,1 wk ahead inc case,2021-05-22,Alabama,Alabama,01,6995,43,474,6382,50140
2,ESG,2021-05-17,1 wk ahead inc case,2021-05-22,Alabama,Alabama,01,3455,1414,2753,4157,5496
3,MOBS,2021-05-17,1 wk ahead inc case,2021-05-22,Alabama,Alabama,01,4709,2154,3545,6188,8844
4,LANL,2021-05-17,1 wk ahead inc case,2021-05-22,Alabama,Alabama,01,1877,326,957,3448,8671

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,BPagano,2021-05-17,1 wk ahead inc case,2021-05-22,Alabama,Alabama,01,2134,0,1348,2886,4333
1,JHU-IDD,2021-05-17,1 wk ahead inc case,2021-05-22,Alabama,Alabama,01,6995,43,474,6382,50140
2,ESG,2021-05-17,1 wk ahead inc case,2021-05-22,Alabama,Alabama,01,3455,1414,2753,4157,5496
3,MOBS,2021-05-17,1 wk ahead inc case,2021-05-22,Alabama,Alabama,01,4709,2154,3545,6188,8844
4,LANL,2021-05-17,1 wk ahead inc case,2021-05-22,Alabama,Alabama,01,1877,326,957,3448,8671

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
21,Ensemble,2021-05-17,1 wk ahead inc case,2021-05-22,Autauga,Alabama,01001,25,2,16,56,110
22,UGA-CEID,2021-05-17,1 wk ahead inc case,2021-05-22,Autauga,Alabama,01001,90,0,45,129,273
23,UpstateSU,2021-05-17,1 wk ahead inc case,2021-05-22,Autauga,Alabama,01001,83,67,79,90,95
24,LNQ,2021-05-17,1 wk ahead inc case,2021-05-22,Autauga,Alabama,01001,43,4,21,73,184
25,JHU-UNC-Google,2021-05-17,1 wk ahead inc case,2021-05-22,Autauga,Alabama,01001,59,0,35,95,182
...,...,...,...,...,...,...,...,...,...,...,...,...
148155,Facebook,2021-05-17,4 wk ahead inc case,2021-06-12,Weston,Wyoming,56045,2,0,0,8,17
148156,LANL,2021-05-17,4 wk ahead inc case,2021-06-12,Weston,Wyoming,56045,2,0,0,3,8
148157,UVA,2021-05-17,4 wk ahead inc case,2021-06-12,Weston,Wyoming,56045,0,0,0,1,2
148158,JHU-UNC-Google,2021-05-17,4 wk ahead inc case,2021-06-12,Weston,Wyoming,56045,0,0,0,7,22
148159,UGA-CEID,2021-05-17,4 wk ahead inc case,2021-06-12,Weston,Wyoming,56045,0,0,0,4,10

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)