In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-03-22-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

C:\Users\Doug Smith\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,Ensemble,2021-03-22,1 wk ahead inc case,2021-03-27,Alabama,Alabama,01,4613,2466,3625,5875,8443
1,UCLA,2021-03-22,1 wk ahead inc case,2021-03-27,Alabama,Alabama,01,9186,7828,8810,9533,11669
2,Columbia,2021-03-22,1 wk ahead inc case,2021-03-27,Alabama,Alabama,01,2951,2406,2754,3164,3614
3,UVA,2021-03-22,1 wk ahead inc case,2021-03-27,Alabama,Alabama,01,6864,0,4441,9288,13905
4,Microsoft,2021-03-22,1 wk ahead inc case,2021-03-27,Alabama,Alabama,01,6143,5076,5778,6550,7449

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,Ensemble,2021-03-22,1 wk ahead inc case,2021-03-27,Alabama,Alabama,01,4613,2466,3625,5875,8443
1,UCLA,2021-03-22,1 wk ahead inc case,2021-03-27,Alabama,Alabama,01,9186,7828,8810,9533,11669
2,Columbia,2021-03-22,1 wk ahead inc case,2021-03-27,Alabama,Alabama,01,2951,2406,2754,3164,3614
3,UVA,2021-03-22,1 wk ahead inc case,2021-03-27,Alabama,Alabama,01,6864,0,4441,9288,13905
4,Microsoft,2021-03-22,1 wk ahead inc case,2021-03-27,Alabama,Alabama,01,6143,5076,5778,6550,7449

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
24,Columbia,2021-03-22,1 wk ahead inc case,2021-03-27,Autauga,Alabama,01001,39,9,26,49,75
25,LANL,2021-03-22,1 wk ahead inc case,2021-03-27,Autauga,Alabama,01001,25,3,10,50,129
26,UGA-CEID,2021-03-22,1 wk ahead inc case,2021-03-27,Autauga,Alabama,01001,99,6,67,127,231
27,Ensemble,2021-03-22,1 wk ahead inc case,2021-03-27,Autauga,Alabama,01001,63,4,40,79,118
28,JHU-UNC-Google,2021-03-22,1 wk ahead inc case,2021-03-27,Autauga,Alabama,01001,60,0,28,134,213
...,...,...,...,...,...,...,...,...,...,...,...,...
147667,Econometric,2021-03-22,4 wk ahead inc case,2021-04-17,Weston,Wyoming,56045,1,0,0,2,7
147668,UVA,2021-03-22,4 wk ahead inc case,2021-04-17,Weston,Wyoming,56045,0,0,0,0,0
147669,LANL,2021-03-22,4 wk ahead inc case,2021-04-17,Weston,Wyoming,56045,1,0,0,4,13
147670,ISU,2021-03-22,4 wk ahead inc case,2021-04-17,Weston,Wyoming,56045,18,0,14,22,30
147671,UGA-CEID,2021-03-22,4 wk ahead inc case,2021-04-17,Weston,Wyoming,56045,0,0,0,7,31

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)