In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-08-23-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,BPagano,2021-08-23,1 wk ahead inc case,2021-08-28,Alabama,Alabama,01,30946,3580,21319,40151,57890
1,MIT-ISOLAT,2021-08-23,1 wk ahead inc case,2021-08-28,Alabama,Alabama,01,24783,0,16254,33312,49566
2,Ensemble,2021-08-23,1 wk ahead inc case,2021-08-28,Alabama,Alabama,01,28246,18476,25183,33373,40149
3,MOBS,2021-08-23,1 wk ahead inc case,2021-08-28,Alabama,Alabama,01,24621,14563,21076,28185,36199
4,Covid19Sim,2021-08-23,1 wk ahead inc case,2021-08-28,Alabama,Alabama,01,27495,27198,27460,27556,28555

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,BPagano,2021-08-23,1 wk ahead inc case,2021-08-28,Alabama,Alabama,01,30946,3580,21319,40151,57890
1,MIT-ISOLAT,2021-08-23,1 wk ahead inc case,2021-08-28,Alabama,Alabama,01,24783,0,16254,33312,49566
2,Ensemble,2021-08-23,1 wk ahead inc case,2021-08-28,Alabama,Alabama,01,28246,18476,25183,33373,40149
3,MOBS,2021-08-23,1 wk ahead inc case,2021-08-28,Alabama,Alabama,01,24621,14563,21076,28185,36199
4,Covid19Sim,2021-08-23,1 wk ahead inc case,2021-08-28,Alabama,Alabama,01,27495,27198,27460,27556,28555

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
21,Columbia,2021-08-23,1 wk ahead inc case,2021-08-28,Autauga,Alabama,01001,235,112,189,279,379
22,FRBSF-Wilson,2021-08-23,1 wk ahead inc case,2021-08-28,Autauga,Alabama,01001,207,72,152,280,591
23,JHU-UNC-Google,2021-08-23,1 wk ahead inc case,2021-08-28,Autauga,Alabama,01001,280,23,233,425,2523
24,UGA-CEID,2021-08-23,1 wk ahead inc case,2021-08-28,Autauga,Alabama,01001,191,107,161,216,309
25,Facebook,2021-08-23,1 wk ahead inc case,2021-08-28,Autauga,Alabama,01001,199,22,138,260,376
...,...,...,...,...,...,...,...,...,...,...,...,...
111311,Ensemble,2021-08-23,4 wk ahead inc case,2021-09-18,Weston,Wyoming,56045,18,0,8,32,72
111312,Columbia,2021-08-23,4 wk ahead inc case,2021-09-18,Weston,Wyoming,56045,0,0,0,1,14
111313,UGA-CEID,2021-08-23,4 wk ahead inc case,2021-09-18,Weston,Wyoming,56045,11,0,5,17,28
111314,JHU-UNC-Google,2021-08-23,4 wk ahead inc case,2021-09-18,Weston,Wyoming,56045,27,0,7,64,199
111315,UVA,2021-08-23,4 wk ahead inc case,2021-09-18,Weston,Wyoming,56045,173,161,168,178,185

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)