In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-02-01-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,USC,2021-02-01,1 wk ahead inc case,2021-02-06,Alabama,Alabama,01,19320,12483,13672,19658,19900
1,JHU-UNC-Google,2021-02-01,1 wk ahead inc case,2021-02-06,Alabama,Alabama,01,17806,5610,15475,21200,33797
2,JHU-CSSE,2021-02-01,1 wk ahead inc case,2021-02-06,Alabama,Alabama,01,18024,12862,15176,19545,24253
3,MIT-ORC,2021-02-01,1 wk ahead inc case,2021-02-06,Alabama,Alabama,01,14198,8994,12407,15989,19402
4,BPagano,2021-02-01,1 wk ahead inc case,2021-02-06,Alabama,Alabama,01,15835,5684,12264,19250,25830

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,USC,2021-02-01,1 wk ahead inc case,2021-02-06,Alabama,Alabama,01,19320,12483,13672,19658,19900
1,JHU-UNC-Google,2021-02-01,1 wk ahead inc case,2021-02-06,Alabama,Alabama,01,17806,5610,15475,21200,33797
2,JHU-CSSE,2021-02-01,1 wk ahead inc case,2021-02-06,Alabama,Alabama,01,18024,12862,15176,19545,24253
3,MIT-ORC,2021-02-01,1 wk ahead inc case,2021-02-06,Alabama,Alabama,01,14198,8994,12407,15989,19402
4,BPagano,2021-02-01,1 wk ahead inc case,2021-02-06,Alabama,Alabama,01,15835,5684,12264,19250,25830

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
24,Facebook,2021-02-01,1 wk ahead inc case,2021-02-06,Autauga,Alabama,01001,181,82,146,215,279
25,Ensemble,2021-02-01,1 wk ahead inc case,2021-02-06,Autauga,Alabama,01001,223,82,146,265,354
26,OneQuietNight,2021-02-01,1 wk ahead inc case,2021-02-06,Autauga,Alabama,01001,170,0,85,231,394
27,LNQ,2021-02-01,1 wk ahead inc case,2021-02-06,Autauga,Alabama,01001,249,89,191,318,572
28,JHU-APL,2021-02-01,1 wk ahead inc case,2021-02-06,Autauga,Alabama,01001,120,83,105,136,167
...,...,...,...,...,...,...,...,...,...,...,...,...
156299,PandemicCentral,2021-02-01,4 wk ahead inc case,2021-02-27,Weston,Wyoming,56045,13,4,8,17,24
156300,UGA-CEID,2021-02-01,4 wk ahead inc case,2021-02-27,Weston,Wyoming,56045,1,0,0,152,390
156301,Ensemble,2021-02-01,4 wk ahead inc case,2021-02-27,Weston,Wyoming,56045,7,0,0,16,34
156302,JHU-APL,2021-02-01,4 wk ahead inc case,2021-02-27,Weston,Wyoming,56045,0,0,0,1,1
156303,LNQ,2021-02-01,4 wk ahead inc case,2021-02-27,Weston,Wyoming,56045,7,0,2,20,98

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)