In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-03-15-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

C:\Users\Doug Smith\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,UM,2021-03-15,1 wk ahead inc case,2021-03-20,Alabama,Alabama,01,3156,280,2004,4396,6493
1,MIT-ORC,2021-03-15,1 wk ahead inc case,2021-03-20,Alabama,Alabama,01,1959,0,639,3279,5795
2,SignatureScience,2021-03-15,1 wk ahead inc case,2021-03-20,Alabama,Alabama,01,3559,0,1779,5339,8731
3,ISU,2021-03-15,1 wk ahead inc case,2021-03-20,Alabama,Alabama,01,3934,3767,3876,3995,4089
4,Karlen,2021-03-15,1 wk ahead inc case,2021-03-20,Alabama,Alabama,01,3628,2493,3177,4689,7560

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,UM,2021-03-15,1 wk ahead inc case,2021-03-20,Alabama,Alabama,01,3156,280,2004,4396,6493
1,MIT-ORC,2021-03-15,1 wk ahead inc case,2021-03-20,Alabama,Alabama,01,1959,0,639,3279,5795
2,SignatureScience,2021-03-15,1 wk ahead inc case,2021-03-20,Alabama,Alabama,01,3559,0,1779,5339,8731
3,ISU,2021-03-15,1 wk ahead inc case,2021-03-20,Alabama,Alabama,01,3934,3767,3876,3995,4089
4,Karlen,2021-03-15,1 wk ahead inc case,2021-03-20,Alabama,Alabama,01,3628,2493,3177,4689,7560

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
23,Facebook,2021-03-15,1 wk ahead inc case,2021-03-20,Autauga,Alabama,01001,62,0,40,84,124
24,Columbia,2021-03-15,1 wk ahead inc case,2021-03-20,Autauga,Alabama,01001,50,17,37,64,97
25,Ensemble,2021-03-15,1 wk ahead inc case,2021-03-20,Autauga,Alabama,01001,62,10,37,84,179
26,LANL,2021-03-15,1 wk ahead inc case,2021-03-20,Autauga,Alabama,01001,52,10,29,85,179
27,LNQ,2021-03-15,1 wk ahead inc case,2021-03-20,Autauga,Alabama,01001,58,10,35,89,193
...,...,...,...,...,...,...,...,...,...,...,...,...
145383,ISU,2021-03-15,4 wk ahead inc case,2021-04-10,Weston,Wyoming,56045,3,0,2,4,6
145384,LNQ,2021-03-15,4 wk ahead inc case,2021-04-10,Weston,Wyoming,56045,3,0,0,14,71
145385,UVA,2021-03-15,4 wk ahead inc case,2021-04-10,Weston,Wyoming,56045,10,8,9,11,12
145386,LANL,2021-03-15,4 wk ahead inc case,2021-04-10,Weston,Wyoming,56045,2,0,1,4,12
145387,Columbia,2021-03-15,4 wk ahead inc case,2021-04-10,Weston,Wyoming,56045,0,0,0,1,14

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)