In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-04-12-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,ESG,2021-04-12,1 wk ahead inc case,2021-04-17,Alabama,Alabama,01,1927,221,1340,2513,3632
1,Ensemble,2021-04-12,1 wk ahead inc case,2021-04-17,Alabama,Alabama,01,1927,636,1437,2449,3632
2,USC,2021-04-12,1 wk ahead inc case,2021-04-17,Alabama,Alabama,01,1721,1488,1602,1832,2327
3,JHU-IDD,2021-04-12,1 wk ahead inc case,2021-04-17,Alabama,Alabama,01,4887,1514,2781,5962,13632
4,UGA-CEID,2021-04-12,1 wk ahead inc case,2021-04-17,Alabama,Alabama,01,1431,0,0,3765,7313

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,ESG,2021-04-12,1 wk ahead inc case,2021-04-17,Alabama,Alabama,01,1927,221,1340,2513,3632
1,Ensemble,2021-04-12,1 wk ahead inc case,2021-04-17,Alabama,Alabama,01,1927,636,1437,2449,3632
2,USC,2021-04-12,1 wk ahead inc case,2021-04-17,Alabama,Alabama,01,1721,1488,1602,1832,2327
3,JHU-IDD,2021-04-12,1 wk ahead inc case,2021-04-17,Alabama,Alabama,01,4887,1514,2781,5962,13632
4,UGA-CEID,2021-04-12,1 wk ahead inc case,2021-04-17,Alabama,Alabama,01,1431,0,0,3765,7313

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
23,LANL,2021-04-12,1 wk ahead inc case,2021-04-17,Autauga,Alabama,01001,59,13,35,94,194
24,JHU-UNC-Google,2021-04-12,1 wk ahead inc case,2021-04-17,Autauga,Alabama,01001,52,0,29,132,248
25,Columbia,2021-04-12,1 wk ahead inc case,2021-04-17,Autauga,Alabama,01001,50,17,36,64,93
26,ISU,2021-04-12,1 wk ahead inc case,2021-04-17,Autauga,Alabama,01001,49,37,45,54,64
27,UpstateSU,2021-04-12,1 wk ahead inc case,2021-04-17,Autauga,Alabama,01001,93,87,88,95,97
...,...,...,...,...,...,...,...,...,...,...,...,...
149747,LNQ,2021-04-12,4 wk ahead inc case,2021-05-08,Weston,Wyoming,56045,3,0,0,12,59
149748,JHU-IDD,2021-04-12,4 wk ahead inc case,2021-05-08,Weston,Wyoming,56045,11,0,0,5,109
149749,Facebook,2021-04-12,4 wk ahead inc case,2021-05-08,Weston,Wyoming,56045,5,0,0,14,30
149750,ISU,2021-04-12,4 wk ahead inc case,2021-05-08,Weston,Wyoming,56045,2,0,1,3,6
149751,UVA,2021-04-12,4 wk ahead inc case,2021-05-08,Weston,Wyoming,56045,33,0,16,50,82

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)