In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-04-26-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,Covid19Sim,2021-04-26,1 wk ahead inc case,2021-05-01,Alabama,Alabama,01,3590,3066,3483,3669,3823
1,BPagano,2021-04-26,1 wk ahead inc case,2021-05-01,Alabama,Alabama,01,2413,0,1525,3263,4899
2,Ensemble,2021-04-26,1 wk ahead inc case,2021-05-01,Alabama,Alabama,01,3457,1230,2212,4093,5619
3,IEM,2021-04-26,1 wk ahead inc case,2021-05-01,Alabama,Alabama,01,3418,1599,2664,4388,6620
4,LNQ,2021-04-26,1 wk ahead inc case,2021-05-01,Alabama,Alabama,01,3149,1087,2450,3923,7130

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,Covid19Sim,2021-04-26,1 wk ahead inc case,2021-05-01,Alabama,Alabama,01,3590,3066,3483,3669,3823
1,BPagano,2021-04-26,1 wk ahead inc case,2021-05-01,Alabama,Alabama,01,2413,0,1525,3263,4899
2,Ensemble,2021-04-26,1 wk ahead inc case,2021-05-01,Alabama,Alabama,01,3457,1230,2212,4093,5619
3,IEM,2021-04-26,1 wk ahead inc case,2021-05-01,Alabama,Alabama,01,3418,1599,2664,4388,6620
4,LNQ,2021-04-26,1 wk ahead inc case,2021-05-01,Alabama,Alabama,01,3149,1087,2450,3923,7130

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
22,ISU,2021-04-26,1 wk ahead inc case,2021-05-01,Autauga,Alabama,01001,50,35,45,55,67
23,UGA-CEID,2021-04-26,1 wk ahead inc case,2021-05-01,Autauga,Alabama,01001,121,30,89,149,250
24,LNQ,2021-04-26,1 wk ahead inc case,2021-05-01,Autauga,Alabama,01001,77,9,46,112,230
25,JHU-UNC-Google,2021-04-26,1 wk ahead inc case,2021-05-01,Autauga,Alabama,01001,58,0,32,120,283
26,FRBSF-Wilson,2021-04-26,1 wk ahead inc case,2021-05-01,Autauga,Alabama,01001,36,19,30,44,67
...,...,...,...,...,...,...,...,...,...,...,...,...
155947,Ensemble,2021-04-26,4 wk ahead inc case,2021-05-22,Weston,Wyoming,56045,2,0,0,6,15
155948,UVA,2021-04-26,4 wk ahead inc case,2021-05-22,Weston,Wyoming,56045,2,0,1,4,6
155949,LANL,2021-04-26,4 wk ahead inc case,2021-05-22,Weston,Wyoming,56045,3,0,1,5,10
155950,UGA-CEID,2021-04-26,4 wk ahead inc case,2021-05-22,Weston,Wyoming,56045,3,0,0,7,16
155951,Columbia,2021-04-26,4 wk ahead inc case,2021-05-22,Weston,Wyoming,56045,0,0,0,0,14

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)