In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-05-24-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,Ensemble,2021-05-24,1 wk ahead inc case,2021-05-29,Alabama,Alabama,01,2310,743,1894,3884,6348
1,BPagano,2021-05-24,1 wk ahead inc case,2021-05-29,Alabama,Alabama,01,3486,0,2203,4713,7076
2,MIT-ORC,2021-05-24,1 wk ahead inc case,2021-05-29,Alabama,Alabama,01,7488,1403,5394,9582,13573
3,LANL,2021-05-24,1 wk ahead inc case,2021-05-29,Alabama,Alabama,01,1532,260,766,2856,7551
4,MOBS,2021-05-24,1 wk ahead inc case,2021-05-29,Alabama,Alabama,01,5307,2568,4122,7097,12927

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,Ensemble,2021-05-24,1 wk ahead inc case,2021-05-29,Alabama,Alabama,01,2310,743,1894,3884,6348
1,BPagano,2021-05-24,1 wk ahead inc case,2021-05-29,Alabama,Alabama,01,3486,0,2203,4713,7076
2,MIT-ORC,2021-05-24,1 wk ahead inc case,2021-05-29,Alabama,Alabama,01,7488,1403,5394,9582,13573
3,LANL,2021-05-24,1 wk ahead inc case,2021-05-29,Alabama,Alabama,01,1532,260,766,2856,7551
4,MOBS,2021-05-24,1 wk ahead inc case,2021-05-29,Alabama,Alabama,01,5307,2568,4122,7097,12927

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
21,Ensemble,2021-05-24,1 wk ahead inc case,2021-05-29,Autauga,Alabama,01001,80,5,43,119,243
22,UGA-CEID,2021-05-24,1 wk ahead inc case,2021-05-29,Autauga,Alabama,01001,118,4,79,153,280
23,FRBSF-Wilson,2021-05-24,1 wk ahead inc case,2021-05-29,Autauga,Alabama,01001,82,49,71,96,137
24,LANL,2021-05-24,1 wk ahead inc case,2021-05-29,Autauga,Alabama,01001,78,15,45,125,279
25,LNQ,2021-05-24,1 wk ahead inc case,2021-05-29,Autauga,Alabama,01001,66,6,36,114,237
...,...,...,...,...,...,...,...,...,...,...,...,...
111827,UGA-CEID,2021-05-24,4 wk ahead inc case,2021-06-19,Weston,Wyoming,56045,1,0,0,3,6
111828,LANL,2021-05-24,4 wk ahead inc case,2021-06-19,Weston,Wyoming,56045,1,0,0,2,5
111829,PandemicCentral,2021-05-24,4 wk ahead inc case,2021-06-19,Weston,Wyoming,56045,4,0,0,7,17
111830,LNQ,2021-05-24,4 wk ahead inc case,2021-06-19,Weston,Wyoming,56045,0,0,0,1,21
111831,Facebook,2021-05-24,4 wk ahead inc case,2021-06-19,Weston,Wyoming,56045,3,0,0,8,17

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)