In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-06-21-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,MIT-Cassandra,2021-06-21,1 wk ahead inc case,2021-06-26,Alabama,Alabama,01,1179,0,209,2149,3996
1,Ensemble,2021-06-21,1 wk ahead inc case,2021-06-26,Alabama,Alabama,01,1266,338,886,1597,2316
2,JHU-APL,2021-06-21,1 wk ahead inc case,2021-06-26,Alabama,Alabama,01,927,580,783,1093,1468
3,UCLA,2021-06-21,1 wk ahead inc case,2021-06-26,Alabama,Alabama,01,1644,1325,1517,1915,2882
4,UM,2021-06-21,1 wk ahead inc case,2021-06-26,Alabama,Alabama,01,2080,0,772,2432,3875

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,MIT-Cassandra,2021-06-21,1 wk ahead inc case,2021-06-26,Alabama,Alabama,01,1179,0,209,2149,3996
1,Ensemble,2021-06-21,1 wk ahead inc case,2021-06-26,Alabama,Alabama,01,1266,338,886,1597,2316
2,JHU-APL,2021-06-21,1 wk ahead inc case,2021-06-26,Alabama,Alabama,01,927,580,783,1093,1468
3,UCLA,2021-06-21,1 wk ahead inc case,2021-06-26,Alabama,Alabama,01,1644,1325,1517,1915,2882
4,UM,2021-06-21,1 wk ahead inc case,2021-06-26,Alabama,Alabama,01,2080,0,772,2432,3875

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
22,Columbia,2021-06-21,1 wk ahead inc case,2021-06-26,Autauga,Alabama,01001,5,0,0,9,22
23,FRBSF-Wilson,2021-06-21,1 wk ahead inc case,2021-06-26,Autauga,Alabama,01001,24,8,18,33,67
24,LANL,2021-06-21,1 wk ahead inc case,2021-06-26,Autauga,Alabama,01001,34,9,24,47,74
25,Facebook,2021-06-21,1 wk ahead inc case,2021-06-26,Autauga,Alabama,01001,12,0,2,22,39
26,JHU-UNC-Google,2021-06-21,1 wk ahead inc case,2021-06-26,Autauga,Alabama,01001,48,0,20,92,150
...,...,...,...,...,...,...,...,...,...,...,...,...
111951,UGA-CEID,2021-06-21,4 wk ahead inc case,2021-07-17,Weston,Wyoming,56045,0,0,0,2,5
111952,JHU-UNC-Google,2021-06-21,4 wk ahead inc case,2021-07-17,Weston,Wyoming,56045,0,0,0,2,15
111953,UVA,2021-06-21,4 wk ahead inc case,2021-07-17,Weston,Wyoming,56045,1,0,0,1,2
111954,LANL,2021-06-21,4 wk ahead inc case,2021-07-17,Weston,Wyoming,56045,1,0,0,2,5
111955,Ensemble,2021-06-21,4 wk ahead inc case,2021-07-17,Weston,Wyoming,56045,0,0,0,2,6

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)