In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-02-15-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,LNQ,2/15/2021,1 wk ahead inc case,2/20/2021,Alabama,Alabama,1,7242,3649,6129,8379,12997
1,Ensemble,2/15/2021,1 wk ahead inc case,2/20/2021,Alabama,Alabama,1,8168,4625,6761,9604,12908
2,Microsoft,2/15/2021,1 wk ahead inc case,2/20/2021,Alabama,Alabama,1,7686,6701,7146,8186,8474
3,OneQuietNight,2/15/2021,1 wk ahead inc case,2/20/2021,Alabama,Alabama,1,5986,0,3882,8180,11845
4,BPagano,2/15/2021,1 wk ahead inc case,2/20/2021,Alabama,Alabama,1,11110,4711,8859,13262,17409

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,LNQ,2/15/2021,1 wk ahead inc case,2/20/2021,Alabama,Alabama,1,7242,3649,6129,8379,12997
1,Ensemble,2/15/2021,1 wk ahead inc case,2/20/2021,Alabama,Alabama,1,8168,4625,6761,9604,12908
2,Microsoft,2/15/2021,1 wk ahead inc case,2/20/2021,Alabama,Alabama,1,7686,6701,7146,8186,8474
3,OneQuietNight,2/15/2021,1 wk ahead inc case,2/20/2021,Alabama,Alabama,1,5986,0,3882,8180,11845
4,BPagano,2/15/2021,1 wk ahead inc case,2/20/2021,Alabama,Alabama,1,11110,4711,8859,13262,17409

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
24,Columbia,2/15/2021,1 wk ahead inc case,2/20/2021,Autauga,Alabama,1001,145,81,122,172,221
25,JHU-APL,2/15/2021,1 wk ahead inc case,2/20/2021,Autauga,Alabama,1001,164,105,141,191,241
26,Ensemble,2/15/2021,1 wk ahead inc case,2/20/2021,Autauga,Alabama,1001,130,35,98,180,296
27,UGA-CEID,2/15/2021,1 wk ahead inc case,2/20/2021,Autauga,Alabama,1001,154,19,107,194,343
28,OneQuietNight,2/15/2021,1 wk ahead inc case,2/20/2021,Autauga,Alabama,1001,133,0,56,212,377
...,...,...,...,...,...,...,...,...,...,...,...,...
176319,PandemicCentral,2/15/2021,4 wk ahead inc case,3/13/2021,Weston,Wyoming,56045,1,0,0,1,5
176320,LNQ,2/15/2021,4 wk ahead inc case,3/13/2021,Weston,Wyoming,56045,1,0,0,9,59
176321,ISU,2/15/2021,4 wk ahead inc case,3/13/2021,Weston,Wyoming,56045,13,5,10,15,21
176322,OneQuietNight,2/15/2021,4 wk ahead inc case,3/13/2021,Weston,Wyoming,56045,17,0,5,30,55
176323,UGA-CEID,2/15/2021,4 wk ahead inc case,3/13/2021,Weston,Wyoming,56045,22,0,0,84,232

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)