In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-10-04-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,USC,2021-10-04,1 wk ahead inc case,2021-10-09,Alabama,Alabama,01,9456,7713,8842,10248,11156
1,JHU-APL,2021-10-04,1 wk ahead inc case,2021-10-09,Alabama,Alabama,01,10501,6133,8674,12635,17012
2,Columbia,2021-10-04,1 wk ahead inc case,2021-10-09,Alabama,Alabama,01,13298,9936,12149,14597,17647
3,MIT-ISOLAT,2021-10-04,1 wk ahead inc case,2021-10-09,Alabama,Alabama,01,10909,0,7154,14663,21817
4,BPagano,2021-10-04,1 wk ahead inc case,2021-10-09,Alabama,Alabama,01,11112,3775,8531,13579,18335

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,USC,2021-10-04,1 wk ahead inc case,2021-10-09,Alabama,Alabama,01,9456,7713,8842,10248,11156
1,JHU-APL,2021-10-04,1 wk ahead inc case,2021-10-09,Alabama,Alabama,01,10501,6133,8674,12635,17012
2,Columbia,2021-10-04,1 wk ahead inc case,2021-10-09,Alabama,Alabama,01,13298,9936,12149,14597,17647
3,MIT-ISOLAT,2021-10-04,1 wk ahead inc case,2021-10-09,Alabama,Alabama,01,10909,0,7154,14663,21817
4,BPagano,2021-10-04,1 wk ahead inc case,2021-10-09,Alabama,Alabama,01,11112,3775,8531,13579,18335

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
19,Facebook,2021-10-04,1 wk ahead inc case,2021-10-09,Autauga,Alabama,01001,114,0,62,167,267
20,PandemicCentral,2021-10-04,1 wk ahead inc case,2021-10-09,Autauga,Alabama,01001,158,94,138,169,242
21,Columbia,2021-10-04,1 wk ahead inc case,2021-10-09,Autauga,Alabama,01001,102,33,77,127,183
22,UVA,2021-10-04,1 wk ahead inc case,2021-10-09,Autauga,Alabama,01001,117,59,97,137,175
23,UGA-CEID,2021-10-04,1 wk ahead inc case,2021-10-09,Autauga,Alabama,01001,127,83,112,141,190
...,...,...,...,...,...,...,...,...,...,...,...,...
122939,Facebook,2021-10-04,4 wk ahead inc case,2021-10-30,Weston,Wyoming,56045,8,0,0,23,51
122940,JHU-UNC-Google,2021-10-04,4 wk ahead inc case,2021-10-30,Weston,Wyoming,56045,14,0,0,29,87
122941,PandemicCentral,2021-10-04,4 wk ahead inc case,2021-10-30,Weston,Wyoming,56045,26,7,16,32,57
122942,JHU-APL,2021-10-04,4 wk ahead inc case,2021-10-30,Weston,Wyoming,56045,13,4,8,18,32
122943,UVA,2021-10-04,4 wk ahead inc case,2021-10-30,Weston,Wyoming,56045,27,8,20,34,46

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)