In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-11-08-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,IEM,2021-11-08,1 wk ahead inc case,2021-11-13,Alabama,Alabama,01,4550,1088,3223,5806,8298
1,USC,2021-11-08,1 wk ahead inc case,2021-11-13,Alabama,Alabama,01,6495,5094,5915,7091,8255
2,Karlen,2021-11-08,1 wk ahead inc case,2021-11-13,Alabama,Alabama,01,3431,2067,2926,4116,5468
3,MIT-ISOLAT,2021-11-08,1 wk ahead inc case,2021-11-13,Alabama,Alabama,01,884,0,579,1188,1768
4,UM,2021-11-08,1 wk ahead inc case,2021-11-13,Alabama,Alabama,01,9727,5442,8157,11509,14797

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,IEM,2021-11-08,1 wk ahead inc case,2021-11-13,Alabama,Alabama,01,4550,1088,3223,5806,8298
1,USC,2021-11-08,1 wk ahead inc case,2021-11-13,Alabama,Alabama,01,6495,5094,5915,7091,8255
2,Karlen,2021-11-08,1 wk ahead inc case,2021-11-13,Alabama,Alabama,01,3431,2067,2926,4116,5468
3,MIT-ISOLAT,2021-11-08,1 wk ahead inc case,2021-11-13,Alabama,Alabama,01,884,0,579,1188,1768
4,UM,2021-11-08,1 wk ahead inc case,2021-11-13,Alabama,Alabama,01,9727,5442,8157,11509,14797

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
16,Columbia,2021-11-08,1 wk ahead inc case,2021-11-13,Autauga,Alabama,01001,128,40,91,174,254
17,Ensemble,2021-11-08,1 wk ahead inc case,2021-11-13,Autauga,Alabama,01001,96,31,81,121,211
18,JHU-UNC-Google,2021-11-08,1 wk ahead inc case,2021-11-13,Autauga,Alabama,01001,76,0,47,122,179
19,FRBSF-Wilson,2021-11-08,1 wk ahead inc case,2021-11-13,Autauga,Alabama,01001,201,93,161,250,436
20,PandemicCentral,2021-11-08,1 wk ahead inc case,2021-11-13,Autauga,Alabama,01001,98,24,78,120,183
...,...,...,...,...,...,...,...,...,...,...,...,...
97355,PandemicCentral,2021-11-08,4 wk ahead inc case,2021-12-04,Weston,Wyoming,56045,19,0,5,27,59
97356,Facebook,2021-11-08,4 wk ahead inc case,2021-12-04,Weston,Wyoming,56045,21,0,0,46,93
97357,CUBoulder,2021-11-08,4 wk ahead inc case,2021-12-04,Weston,Wyoming,56045,20,5,13,31,69
97358,Columbia,2021-11-08,4 wk ahead inc case,2021-12-04,Weston,Wyoming,56045,7,0,0,14,35
97359,JHU-UNC-Google,2021-11-08,4 wk ahead inc case,2021-12-04,Weston,Wyoming,56045,28,0,7,61,137

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)