In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-06-14-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,Ensemble,2021-06-14,1 wk ahead inc case,2021-06-19,Alabama,Alabama,01,1656,615,1156,2233,3165
1,Microsoft,2021-06-14,1 wk ahead inc case,2021-06-19,Alabama,Alabama,01,1612,954,1451,1778,2071
2,BPagano,2021-06-14,1 wk ahead inc case,2021-06-19,Alabama,Alabama,01,1405,0,888,1900,2853
3,JHU-CSSE,2021-06-14,1 wk ahead inc case,2021-06-19,Alabama,Alabama,01,2198,928,1751,2721,3395
4,MIT-Cassandra,2021-06-14,1 wk ahead inc case,2021-06-19,Alabama,Alabama,01,1562,0,466,2658,4746

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,Ensemble,2021-06-14,1 wk ahead inc case,2021-06-19,Alabama,Alabama,01,1656,615,1156,2233,3165
1,Microsoft,2021-06-14,1 wk ahead inc case,2021-06-19,Alabama,Alabama,01,1612,954,1451,1778,2071
2,BPagano,2021-06-14,1 wk ahead inc case,2021-06-19,Alabama,Alabama,01,1405,0,888,1900,2853
3,JHU-CSSE,2021-06-14,1 wk ahead inc case,2021-06-19,Alabama,Alabama,01,2198,928,1751,2721,3395
4,MIT-Cassandra,2021-06-14,1 wk ahead inc case,2021-06-19,Alabama,Alabama,01,1562,0,466,2658,4746

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
23,Columbia,2021-06-14,1 wk ahead inc case,2021-06-19,Autauga,Alabama,01001,7,0,4,14,36
24,FRBSF-Wilson,2021-06-14,1 wk ahead inc case,2021-06-19,Autauga,Alabama,01001,24,10,18,30,50
25,UGA-CEID,2021-06-14,1 wk ahead inc case,2021-06-19,Autauga,Alabama,01001,34,0,4,59,153
26,Ensemble,2021-06-14,1 wk ahead inc case,2021-06-19,Autauga,Alabama,01001,29,0,5,42,133
27,Facebook,2021-06-14,1 wk ahead inc case,2021-06-19,Autauga,Alabama,01001,12,0,3,21,37
...,...,...,...,...,...,...,...,...,...,...,...,...
112099,Facebook,2021-06-14,4 wk ahead inc case,2021-07-10,Weston,Wyoming,56045,1,0,0,4,10
112100,PandemicCentral,2021-06-14,4 wk ahead inc case,2021-07-10,Weston,Wyoming,56045,4,0,0,7,12
112101,JHU-APL,2021-06-14,4 wk ahead inc case,2021-07-10,Weston,Wyoming,56045,1,0,0,1,3
112102,UVA,2021-06-14,4 wk ahead inc case,2021-07-10,Weston,Wyoming,56045,1,0,0,2,2
112103,JHU-UNC-Google,2021-06-14,4 wk ahead inc case,2021-07-10,Weston,Wyoming,56045,0,0,0,2,16

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)