In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format

In [2]:
case_forecast_df = pd.read_csv('2021-11-29-all-forecasted-cases-model-data.csv')
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,JHU-APL,2021-11-29,1 wk ahead inc case,2021-12-04,Alabama,Alabama,01,2523,1557,2140,2949,3823
1,JHU-UNC-Google,2021-11-29,1 wk ahead inc case,2021-12-04,Alabama,Alabama,01,2144,901,1600,2821,7165
2,Columbia,2021-11-29,1 wk ahead inc case,2021-12-04,Alabama,Alabama,01,3213,1630,2485,3925,5264
3,Karlen,2021-11-29,1 wk ahead inc case,2021-12-04,Alabama,Alabama,01,2150,1418,1919,2541,3336
4,Masaryk,2021-11-29,1 wk ahead inc case,2021-12-04,Alabama,Alabama,01,2172,436,1637,3865,7839

In [3]:
case_forecast_df['location_name'] = case_forecast_df['location_name'].apply(lambda x: x.split(' County,')[0])
case_forecast_df = case_forecast_df.fillna(0)
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '5 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '6 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '7 wk ahead inc case')]
case_forecast_df = case_forecast_df[(case_forecast_df['target'] != '8 wk ahead inc case')]
case_forecast_df.head(5)

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
0,JHU-APL,2021-11-29,1 wk ahead inc case,2021-12-04,Alabama,Alabama,01,2523,1557,2140,2949,3823
1,JHU-UNC-Google,2021-11-29,1 wk ahead inc case,2021-12-04,Alabama,Alabama,01,2144,901,1600,2821,7165
2,Columbia,2021-11-29,1 wk ahead inc case,2021-12-04,Alabama,Alabama,01,3213,1630,2485,3925,5264
3,Karlen,2021-11-29,1 wk ahead inc case,2021-12-04,Alabama,Alabama,01,2150,1418,1919,2541,3336
4,Masaryk,2021-11-29,1 wk ahead inc case,2021-12-04,Alabama,Alabama,01,2172,436,1637,3865,7839

In [4]:
case_forecast_df = case_forecast_df.query("State != location_name")
case_forecast_df

,model,forecast_date,target,target_end_date,location_name,State,fips,point,quantile_0.025,quantile_0.25,quantile_0.75,quantile_0.975
16,Facebook,2021-11-29,1 wk ahead inc case,2021-12-04,Autauga,Alabama,01001,44,0,13,75,134
17,JHU-APL,2021-11-29,1 wk ahead inc case,2021-12-04,Autauga,Alabama,01001,60,37,51,71,92
18,Columbia,2021-11-29,1 wk ahead inc case,2021-12-04,Autauga,Alabama,01001,101,32,68,133,184
19,CUBoulder,2021-11-29,1 wk ahead inc case,2021-12-04,Autauga,Alabama,01001,55,16,41,75,135
20,UVA,2021-11-29,1 wk ahead inc case,2021-12-04,Autauga,Alabama,01001,47,0,25,68,107
...,...,...,...,...,...,...,...,...,...,...,...,...
55017,Ensemble,2021-11-29,2 wk ahead inc case,2021-12-11,Weston,Wyoming,56045,1,0,0,10,35
55018,JHU-UNC-Google,2021-11-29,2 wk ahead inc case,2021-12-11,Weston,Wyoming,56045,0,0,0,7,42
55019,CUBoulder,2021-11-29,2 wk ahead inc case,2021-12-11,Weston,Wyoming,56045,6,0,3,11,27
55020,Columbia,2021-11-29,2 wk ahead inc case,2021-12-11,Weston,Wyoming,56045,0,0,0,1,16
55021,UVA,2021-11-29,2 wk ahead inc case,2021-12-11,Weston,Wyoming,56045,0,0,0,32,91

In [5]:
case_forecast_df.to_csv('case_forecast.csv', index=False)