In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
pd.options.display.float_format = '{:.2f}'.format

In [2]:
google_df = pd.read_csv('Global_Mobility_Report.csv', low_memory=False)
google_df['census_fips_code'] = google_df['census_fips_code'].fillna(0).astype(np.int64)
google_df.tail()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
10094699,ZW,Zimbabwe,Midlands Province,Kwekwe,NaN,NaN,0,ChIJRcIZ3-FJNBkRRsj55IcLpfU,2022-05-26,nan,nan,nan,nan,111.00,nan
10094700,ZW,Zimbabwe,Midlands Province,Kwekwe,NaN,NaN,0,ChIJRcIZ3-FJNBkRRsj55IcLpfU,2022-05-27,nan,nan,nan,nan,123.00,nan
10094701,ZW,Zimbabwe,Midlands Province,Kwekwe,NaN,NaN,0,ChIJRcIZ3-FJNBkRRsj55IcLpfU,2022-05-30,nan,nan,nan,nan,116.00,nan
10094702,ZW,Zimbabwe,Midlands Province,Kwekwe,NaN,NaN,0,ChIJRcIZ3-FJNBkRRsj55IcLpfU,2022-05-31,nan,nan,nan,nan,129.00,nan
10094703,ZW,Zimbabwe,Midlands Province,Kwekwe,NaN,NaN,0,ChIJRcIZ3-FJNBkRRsj55IcLpfU,2022-06-01,nan,nan,nan,nan,134.00,nan

In [3]:
us_google = google_df[google_df['country_region'] == 'United States']
us_google["sub_region_2"]= us_google["sub_region_2"].str.replace(" County", "")
us_google["sub_region_2"] = us_google["sub_region_2"].fillna('Statewide')
us_google

<ipython-input-3-85bba7a4b043>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  us_google["sub_region_2"]= us_google["sub_region_2"].str.replace(" County", "")
<ipython-input-3-85bba7a4b043>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  us_google["sub_region_2"] = us_google["sub_region_2"].fillna('Statewide')

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
7837885,US,United States,NaN,Statewide,NaN,NaN,0,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-15,6.00,2.00,15.00,3.00,2.00,-1.00
7837886,US,United States,NaN,Statewide,NaN,NaN,0,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-16,7.00,1.00,16.00,2.00,0.00,-1.00
7837887,US,United States,NaN,Statewide,NaN,NaN,0,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-17,6.00,0.00,28.00,-9.00,-24.00,5.00
7837888,US,United States,NaN,Statewide,NaN,NaN,0,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-18,0.00,-1.00,6.00,1.00,0.00,1.00
7837889,US,United States,NaN,Statewide,NaN,NaN,0,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-19,2.00,0.00,8.00,1.00,1.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996613,US,United States,Wyoming,Weston,NaN,NaN,56045,ChIJd4Rqhed3YocR7ubT5-HgoJg,2022-05-26,nan,nan,nan,nan,-25.00,nan
9996614,US,United States,Wyoming,Weston,NaN,NaN,56045,ChIJd4Rqhed3YocR7ubT5-HgoJg,2022-05-27,nan,nan,nan,nan,-21.00,nan
9996615,US,United States,Wyoming,Weston,NaN,NaN,56045,ChIJd4Rqhed3YocR7ubT5-HgoJg,2022-05-30,nan,nan,nan,nan,-65.00,nan
9996616,US,United States,Wyoming,Weston,NaN,NaN,56045,ChIJd4Rqhed3YocR7ubT5-HgoJg,2022-05-31,nan,nan,nan,nan,-34.00,nan
9996617,US,United States,Wyoming,Weston,NaN,NaN,56045,ChIJd4Rqhed3YocR7ubT5-HgoJg,2022-06-01,nan,nan,nan,nan,-37.00,nan

In [4]:
# us_google = us_google[['country_region_code', 'country_region', 'sub_region_1', 'sub_region_2', 'metro_area', 'iso_3166_2_code', 'date', 'workplaces_percent_change_from_baseline', 'residential_percent_change_from_baseline']]
# us_google

In [5]:
us_google.to_csv('us_google.csv', index=False)