In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
pd.options.display.float_format = '{:.2f}'.format

In [2]:
google_df = pd.read_csv('Global_Mobility_Report.csv', low_memory=False)
google_df['census_fips_code'] = google_df['census_fips_code'].fillna(0).astype(np.int64)
google_df.tail()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
4213716,ZW,Zimbabwe,Midlands Province,Kwekwe,NaN,NaN,0,2021-02-03,nan,nan,nan,nan,-29.00,nan
4213717,ZW,Zimbabwe,Midlands Province,Kwekwe,NaN,NaN,0,2021-02-04,nan,nan,nan,nan,-31.00,nan
4213718,ZW,Zimbabwe,Midlands Province,Kwekwe,NaN,NaN,0,2021-02-05,nan,nan,nan,nan,-27.00,nan
4213719,ZW,Zimbabwe,Midlands Province,Kwekwe,NaN,NaN,0,2021-02-08,nan,nan,nan,nan,-30.00,nan
4213720,ZW,Zimbabwe,Midlands Province,Kwekwe,NaN,NaN,0,2021-02-09,nan,nan,nan,nan,-19.00,nan

In [3]:
us_google = google_df[google_df['country_region'] == 'United States']
us_google["sub_region_2"]= us_google["sub_region_2"].str.replace(" County", "")
us_google

<ipython-input-3-ef2a8e8188a9>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  us_google["sub_region_2"]= us_google["sub_region_2"].str.replace(" County", "")

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
3255445,US,United States,NaN,NaN,NaN,NaN,0,2020-02-15,6.00,2.00,15.00,3.00,2.00,-1.00
3255446,US,United States,NaN,NaN,NaN,NaN,0,2020-02-16,7.00,1.00,16.00,2.00,0.00,-1.00
3255447,US,United States,NaN,NaN,NaN,NaN,0,2020-02-17,6.00,0.00,28.00,-9.00,-24.00,5.00
3255448,US,United States,NaN,NaN,NaN,NaN,0,2020-02-18,0.00,-1.00,6.00,1.00,0.00,1.00
3255449,US,United States,NaN,NaN,NaN,NaN,0,2020-02-19,2.00,0.00,8.00,1.00,1.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4171674,US,United States,Wyoming,Weston,NaN,NaN,56045,2021-02-03,nan,nan,nan,nan,-18.00,nan
4171675,US,United States,Wyoming,Weston,NaN,NaN,56045,2021-02-04,nan,nan,nan,nan,-15.00,nan
4171676,US,United States,Wyoming,Weston,NaN,NaN,56045,2021-02-05,nan,nan,nan,nan,-8.00,nan
4171677,US,United States,Wyoming,Weston,NaN,NaN,56045,2021-02-08,nan,nan,nan,nan,-21.00,nan
4171678,US,United States,Wyoming,Weston,NaN,NaN,56045,2021-02-09,nan,nan,nan,nan,-11.00,nan

In [4]:
# us_google = us_google[['country_region_code', 'country_region', 'sub_region_1', 'sub_region_2', 'metro_area', 'iso_3166_2_code', 'date', 'workplaces_percent_change_from_baseline', 'residential_percent_change_from_baseline']]
# us_google

In [5]:
us_google.to_csv('us_google.csv', index=False)