In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
pd.options.display.float_format = '{:.2f}'.format

In [2]:
positive_df = pd.read_csv('https://raw.githubusercontent.com/datadesk/california-coronavirus-data/master/cdph-positive-test-rate.csv')
positive_df.tail(5)

,date,confirmed_cases,total_tests,new_confirmed_cases,new_positive_tests,new_tests,new_confirmed_cases_seven_day_total,new_tests_seven_day_total,positive_test_rate_seven_day_percent
903,2022-07-23,9884867.00,178824611.00,9374.00,11914.00,59787.00,139778.00,908022.00,0.15
904,2022-07-24,9892593.00,178867992.00,7726.00,8305.00,43381.00,135793.00,892368.00,0.15
905,2022-07-25,9910200.00,178976542.00,17607.00,16713.00,108550.00,124183.00,808076.00,0.15
906,2022-07-26,9920310.00,179044913.00,10110.00,9791.00,68371.00,109310.00,700636.00,0.16
907,2022-07-27,9922203.00,179058899.00,1893.00,2140.00,13986.00,88598.00,559897.00,0.16

In [3]:
bool_series = pd.notnull(positive_df["new_tests_seven_day_total"])
positivity = positive_df[bool_series]
positivity['test'] = 'COVID'
positivity[['confirmed_cases','total_tests','new_confirmed_cases', 'new_positive_tests','new_tests','new_confirmed_cases_seven_day_total','new_tests_seven_day_total']] = positivity[['confirmed_cases','total_tests','new_confirmed_cases', 'new_positive_tests','new_tests','new_confirmed_cases_seven_day_total','new_tests_seven_day_total']].astype(int)
positivity

<ipython-input-3-c4ca47601257>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  positivity['test'] = 'COVID'
C:\Users\Doug Smith\anaconda3\lib\site-packages\pandas\core\frame.py:3065: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

,date,confirmed_cases,total_tests,new_confirmed_cases,new_positive_tests,new_tests,new_confirmed_cases_seven_day_total,new_tests_seven_day_total,positive_test_rate_seven_day_percent,test
6,2020-02-07,82,911,32,62,453,77,911,0.08,COVID
7,2020-02-08,89,970,7,2,59,70,666,0.11,COVID
8,2020-02-09,95,991,6,1,21,69,651,0.11,COVID
9,2020-02-10,101,1007,6,1,16,69,638,0.11,COVID
10,2020-02-11,105,1047,4,0,40,68,646,0.11,COVID
...,...,...,...,...,...,...,...,...,...,...
903,2022-07-23,9884867,178824611,9374,11914,59787,139778,908022,0.15,COVID
904,2022-07-24,9892593,178867992,7726,8305,43381,135793,892368,0.15,COVID
905,2022-07-25,9910200,178976542,17607,16713,108550,124183,808076,0.15,COVID
906,2022-07-26,9920310,179044913,10110,9791,68371,109310,700636,0.16,COVID
907,2022-07-27,9922203,179058899,1893,2140,13986,88598,559897,0.16,COVID

In [4]:
positivity.to_csv('positivity.csv', index=False)