In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
pd.options.display.float_format = '{:.2f}'.format

In [2]:
positive_df = pd.read_csv('https://raw.githubusercontent.com/datadesk/california-coronavirus-data/master/cdph-positive-test-rate.csv')
positive_df.tail(5)

,date,confirmed_cases,total_tests,new_confirmed_cases,new_positive_tests,new_tests,new_confirmed_cases_seven_day_total,new_tests_seven_day_total,positive_test_rate_seven_day_percent
671,2021-12-03,4851511.00,113313516.00,5360.00,7515.00,240269.00,51805.00,2298815.00,0.02
672,2021-12-04,4854547.00,113411567.00,3036.00,4264.00,98051.00,51315.00,2289438.00,0.02
673,2021-12-05,4856893.00,113479913.00,2346.00,2943.00,68346.00,50464.00,2160629.00,0.02
674,2021-12-06,4860420.00,113609001.00,3527.00,3276.00,129088.00,43621.00,1796722.00,0.02
675,2021-12-07,4860946.00,113625934.00,526.00,547.00,16933.00,35272.00,1353981.00,0.03

In [3]:
bool_series = pd.notnull(positive_df["new_tests_seven_day_total"])
positivity = positive_df[bool_series]
positivity['test'] = 'COVID'
positivity

<ipython-input-3-dd681627605a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  positivity['test'] = 'COVID'

,date,confirmed_cases,total_tests,new_confirmed_cases,new_positive_tests,new_tests,new_confirmed_cases_seven_day_total,new_tests_seven_day_total,positive_test_rate_seven_day_percent,test
6,2020-02-07,79.00,904.00,32.00,62.00,452.00,77.00,904.00,0.09,COVID
7,2020-02-08,86.00,961.00,7.00,1.00,57.00,69.00,658.00,0.10,COVID
8,2020-02-09,92.00,982.00,6.00,1.00,21.00,68.00,645.00,0.11,COVID
9,2020-02-10,99.00,998.00,7.00,1.00,16.00,68.00,632.00,0.11,COVID
10,2020-02-11,103.00,1038.00,4.00,0.00,40.00,67.00,641.00,0.10,COVID
...,...,...,...,...,...,...,...,...,...,...
671,2021-12-03,4851511.00,113313516.00,5360.00,7515.00,240269.00,51805.00,2298815.00,0.02,COVID
672,2021-12-04,4854547.00,113411567.00,3036.00,4264.00,98051.00,51315.00,2289438.00,0.02,COVID
673,2021-12-05,4856893.00,113479913.00,2346.00,2943.00,68346.00,50464.00,2160629.00,0.02,COVID
674,2021-12-06,4860420.00,113609001.00,3527.00,3276.00,129088.00,43621.00,1796722.00,0.02,COVID
675,2021-12-07,4860946.00,113625934.00,526.00,547.00,16933.00,35272.00,1353981.00,0.03,COVID

In [4]:
positivity.to_csv('positivity.csv', index=False)