In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
pd.options.display.float_format = '{:.2f}'.format

In [2]:
jail_df = pd.read_csv("https://raw.githubusercontent.com/uclalawcovid19behindbars/data/master/latest-data/adult_facility_covid_counts.csv", low_memory=False)
jail_df = jail_df[['Facility.ID', 'Jurisdiction', 'State', 'Name', 'Address', 'City', 'Zipcode', 'County', 'County.FIPS', 'Latitude', 'Longitude','Residents.Confirmed', 'Staff.Confirmed', 'Residents.Deaths', 'Staff.Deaths', 'Date']].fillna(0)
jail_df['Date'] = pd.to_datetime(jail_df['Date'])
jail_df['Address'] = jail_df['Address'].str.title()
jail_df['City'] = jail_df['City'].str.title()
jail_df['County'] = jail_df['County'].str.title()
jail_df[['Facility.ID','Zipcode', 'County.FIPS', 'Staff.Confirmed', 'Residents.Deaths', 'Staff.Deaths']] = jail_df[['Facility.ID', 'Zipcode','County.FIPS', 'Staff.Confirmed', 'Residents.Deaths', 'Staff.Deaths']].astype(int)
jail_df

,Facility.ID,Jurisdiction,State,Name,Address,City,Zipcode,County,County.FIPS,Latitude,Longitude,Residents.Confirmed,Staff.Confirmed,Residents.Deaths,Staff.Deaths,Date
0,1,state,Alabama,ALABAMA HEADQUARTERS,NaN,NaN,0,NaN,0,0.00,0.00,0.00,68,0,0,2021-02-17
1,2,state,Alabama,ALABAMA TREATMENT AND EDUCATION FACILITY,102 Industrial Parkway,Columbiana,35051,Shelby,1117,33.18,-86.62,11.00,2,1,0,2021-02-17
2,3,state,Alabama,ALEX CITY COMMUNITY BASED FACILITY,Highway 22 West,Alex City,35011,Coosa,1037,32.90,-86.01,75.00,16,0,0,2021-02-17
3,4,federal,Alabama,ALICEVILLE FEDERAL CORRECTIONAL INSTITUTION,11070 Highway 14,Aliceville,35442,Pickens,10107,33.18,-88.19,87.00,0,0,0,2021-02-17
4,5,state,Alabama,BIBB CORRECTIONAL FACILITY,565 Bibb Lane,Brent,35034,Bibb,1007,32.92,-87.16,164.00,60,3,0,2021-02-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1740,0,state,Oklahoma,OK STATE PENITENTIARY,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,0,0,2021-02-17
1741,0,state,Oklahoma,OK STATE REFORMATORY,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,0,0,2021-02-17
1742,0,state,Oklahoma,UNION CITY CCC,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,2,0,2021-02-17
1743,0,state,Pennsylvania,COAL TWNP,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,0,0,2021-02-17
1744,0,state,Pennsylvania,LAUREL HIGH,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,11,0,2021-02-17

In [3]:
jailed = jail_df
jailed2 = jailed[(jailed['Facility.ID'] != 0)]
jailed2 = jailed2.sort_values(by=['Facility.ID'])
jailed2.to_csv('jailed2.csv', index=False)

In [4]:
#jail_df.to_csv('jail.csv', index=False)
jail = jail_df[(jail_df['Facility.ID'] == 0)]
jail.rename({'Facility.ID': 'ID'}, axis=1, inplace=True)
jail

C:\Users\Doug Smith\anaconda3\lib\site-packages\pandas\core\frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,ID,Jurisdiction,State,Name,Address,City,Zipcode,County,County.FIPS,Latitude,Longitude,Residents.Confirmed,Staff.Confirmed,Residents.Deaths,Staff.Deaths,Date
1642,0,county,California,SF COUNTY JAIL,NaN,NaN,0,NaN,0,0.00,0.00,131.00,0,0,0,2021-02-17
1643,0,county,New Mexico,LEA COUNTY DETENTION CENTER,NaN,NaN,0,NaN,0,0.00,0.00,11.00,1,0,0,2021-02-15
1644,0,county,New Mexico,SAN JUAN COUNTY JUVENILE SERVICES,NaN,NaN,0,NaN,0,0.00,0.00,1.00,0,0,0,2021-02-15
1645,0,county,Texas,AUSTIN JAIL,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,0,0,2021-02-17
1646,0,county,Texas,BASTROP JAIL,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,0,0,2021-02-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1740,0,state,Oklahoma,OK STATE PENITENTIARY,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,0,0,2021-02-17
1741,0,state,Oklahoma,OK STATE REFORMATORY,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,0,0,2021-02-17
1742,0,state,Oklahoma,UNION CITY CCC,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,2,0,2021-02-17
1743,0,state,Pennsylvania,COAL TWNP,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,0,0,2021-02-17
1744,0,state,Pennsylvania,LAUREL HIGH,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,11,0,2021-02-17

In [5]:
jail.to_csv('no_id.csv', index=False)

In [6]:
summed = jailed2.groupby(['Facility.ID', 'Date']).sum()
listed = summed.reset_index(drop=False)
listed.rename({'Facility.ID': 'ID'}, axis=1, inplace=True)
listed

,ID,Date,Zipcode,County.FIPS,Latitude,Longitude,Residents.Confirmed,Staff.Confirmed,Residents.Deaths,Staff.Deaths
0,1,2021-02-17,0,0,0.00,0.00,0.00,68,0,0
1,2,2021-02-17,35051,1117,33.18,-86.62,11.00,2,1,0
2,3,2021-02-17,35011,1037,32.90,-86.01,75.00,16,0,0
3,4,2021-02-17,35442,10107,33.18,-88.19,87.00,0,0,0
4,5,2021-02-17,35034,1007,32.92,-87.16,164.00,60,3,0
...,...,...,...,...,...,...,...,...,...,...
1632,2063,2021-02-17,79772,0,31.40,-103.50,0.00,0,1,0
1633,2071,2021-02-15,0,0,0.00,0.00,1.00,0,0,0
1634,2072,2021-02-17,32503,0,30.45,-87.21,6.00,0,0,0
1635,2073,2021-02-17,47711,0,37.98,-87.55,1.00,0,0,0
1636,2074,2021-02-17,23607,0,37.02,-76.45,1.00,0,0,0

In [7]:
listed.to_csv('jailed.csv', index=False)

In [8]:
jailed2

,Facility.ID,Jurisdiction,State,Name,Address,City,Zipcode,County,County.FIPS,Latitude,Longitude,Residents.Confirmed,Staff.Confirmed,Residents.Deaths,Staff.Deaths,Date
0,1,state,Alabama,ALABAMA HEADQUARTERS,NaN,NaN,0,NaN,0,0.00,0.00,0.00,68,0,0,2021-02-17
1,2,state,Alabama,ALABAMA TREATMENT AND EDUCATION FACILITY,102 Industrial Parkway,Columbiana,35051,Shelby,1117,33.18,-86.62,11.00,2,1,0,2021-02-17
2,3,state,Alabama,ALEX CITY COMMUNITY BASED FACILITY,Highway 22 West,Alex City,35011,Coosa,1037,32.90,-86.01,75.00,16,0,0,2021-02-17
3,4,federal,Alabama,ALICEVILLE FEDERAL CORRECTIONAL INSTITUTION,11070 Highway 14,Aliceville,35442,Pickens,10107,33.18,-88.19,87.00,0,0,0,2021-02-17
4,5,state,Alabama,BIBB CORRECTIONAL FACILITY,565 Bibb Lane,Brent,35034,Bibb,1007,32.92,-87.16,164.00,60,3,0,2021-02-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1637,2063,federal,Texas,REEVES III CORRECTIONAL INSTITUTION,100 West County Road # 204,Pecos,79772,NaN,0,31.40,-103.50,0.00,0,1,0,2021-02-17
1638,2071,federal,Not Available,CHASE CENTER - LOCATION UNKNOWN,NaN,NaN,0,NaN,0,0.00,0.00,1.00,0,0,0,2021-02-15
1639,2072,federal,Florida,PENSACOLA RRC,225A Brent Lane,Pensacola,32503,NaN,0,30.45,-87.21,6.00,0,0,0,2021-02-17
1640,2073,federal,Indiana,VOLUNTEERS OF AMERICA INC RRC EVANSVILLE,811 E. Franklin Street,Evansville,47711,NaN,0,37.98,-87.55,1.00,0,0,0,2021-02-17
1641,2074,federal,Virginia,JAMES RIVER RRC,7718 Warwick Blvd.,Newport News,23607,NaN,0,37.02,-76.45,1.00,0,0,0,2021-02-17

In [9]:
jailed.to_csv('all.csv', index=False)