In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
pd.options.display.float_format = '{:.2f}'.format

In [2]:
jail_df = pd.read_csv("https://raw.githubusercontent.com/uclalawcovid19behindbars/data/master/Adult%20Facility%20Counts/adult_facility_covid_counts_today_latest.csv", low_memory=False)
jail_df = jail_df[['Facility.ID', 'jurisdiction', 'State', 'Name', 'Address', 'City', 'Zipcode', 'County', 'County.FIPS', 'Latitude', 'Longitude','Residents.Confirmed', 'Staff.Confirmed', 'Residents.Deaths', 'Staff.Deaths', 'Date']].fillna(0)
jail_df['Date'] = pd.to_datetime(jail_df['Date'])
jail_df['Address'] = jail_df['Address'].str.title()
jail_df['City'] = jail_df['City'].str.title()
jail_df['County'] = jail_df['County'].str.title()
jail_df[['Facility.ID','Zipcode', 'County.FIPS', 'Staff.Confirmed', 'Residents.Deaths', 'Staff.Deaths']] = jail_df[['Facility.ID', 'Zipcode','County.FIPS', 'Staff.Confirmed', 'Residents.Deaths', 'Staff.Deaths']].astype(int)
jail_df

,Facility.ID,jurisdiction,State,Name,Address,City,Zipcode,County,County.FIPS,Latitude,Longitude,Residents.Confirmed,Staff.Confirmed,Residents.Deaths,Staff.Deaths,Date
0,1718,state,Alabama,ALABAMA CORRECTIONS ACADEMY,NaN,NaN,0,NaN,0,32.74,-86.84,0.00,20,0,0,2021-02-01
1,1,state,Alabama,ALABAMA HEADQUARTERS,NaN,NaN,0,NaN,0,0.00,0.00,0.00,66,0,0,2021-02-01
2,2,state,Alabama,ALABAMA TREATMENT AND EDUCATION FACILITY,102 Industrial Parkway,Columbiana,35051,Shelby,1117,33.18,-86.62,10.00,2,1,0,2021-02-01
3,3,state,Alabama,ALEX CITY COMMUNITY BASED FACILITY,Highway 22 West,Alex City,35011,Coosa,1037,32.90,-86.01,4.00,11,0,0,2021-02-01
4,4,federal,Alabama,ALICEVILLE FEDERAL CORRECTIONAL INSTITUTION,11070 Highway 14,Aliceville,35442,Pickens,10107,33.18,-88.19,78.00,0,0,0,2021-02-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1591,0,federal,0,MOSHANNON VALLEY CI,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,3,0,2021-02-01
1592,0,federal,0,NORTH CENTRAL RO,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,0,0,2021-02-01
1593,0,federal,0,REEVES I II CI,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,0,0,2021-02-01
1594,0,federal,0,REEVES III CI,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,1,0,2021-02-01
1595,0,federal,0,VOLUNTEERS OF AMERICA OF IN,NaN,NaN,0,NaN,0,0.00,0.00,1.00,0,0,0,2021-02-01

In [3]:
jailed = jail_df
jailed2 = jailed[(jailed['Facility.ID'] != 0)]
jailed2 = jailed2.sort_values(by=['Facility.ID'])
jailed2.to_csv('jailed2.csv', index=False)

In [4]:
#jail_df.to_csv('jail.csv', index=False)
jail = jail_df[(jail_df['Facility.ID'] == 0)]
jail.rename({'Facility.ID': 'ID'}, axis=1, inplace=True)
jail

C:\Users\Doug Smith\anaconda3\lib\site-packages\pandas\core\frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,ID,jurisdiction,State,Name,Address,City,Zipcode,County,County.FIPS,Latitude,Longitude,Residents.Confirmed,Staff.Confirmed,Residents.Deaths,Staff.Deaths,Date
69,0,state,California,ALMEDA COUNTY,NaN,NaN,0,NaN,0,0.00,0.00,0.00,2,0,0,2021-02-01
98,0,state,California,FRESNO COUNTY,NaN,NaN,0,NaN,0,0.00,0.00,0.00,20,0,0,2021-02-01
106,0,state,California,HUMBOLDT COUNTY,NaN,NaN,0,NaN,0,0.00,0.00,0.00,1,0,0,2021-02-01
107,0,state,California,IMPERIAL COUNTY,NaN,NaN,0,NaN,0,0.00,0.00,0.00,9,0,0,2021-02-01
109,0,state,California,KERN COUNTY,NaN,NaN,0,NaN,0,0.00,0.00,0.00,20,0,0,2021-02-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1591,0,federal,0,MOSHANNON VALLEY CI,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,3,0,2021-02-01
1592,0,federal,0,NORTH CENTRAL RO,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,0,0,2021-02-01
1593,0,federal,0,REEVES I II CI,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,0,0,2021-02-01
1594,0,federal,0,REEVES III CI,NaN,NaN,0,NaN,0,0.00,0.00,0.00,0,1,0,2021-02-01
1595,0,federal,0,VOLUNTEERS OF AMERICA OF IN,NaN,NaN,0,NaN,0,0.00,0.00,1.00,0,0,0,2021-02-01

In [5]:
jail.to_csv('no_id.csv', index=False)

In [6]:
summed = jailed2.groupby(['Facility.ID', 'Date']).sum()
listed = summed.reset_index(drop=False)
listed.rename({'Facility.ID': 'ID'}, axis=1, inplace=True)
listed

,ID,Date,Zipcode,County.FIPS,Latitude,Longitude,Residents.Confirmed,Staff.Confirmed,Residents.Deaths,Staff.Deaths
0,1,2021-02-01,0,0,0.00,0.00,0.00,66,0,0
1,2,2021-02-01,35051,1117,33.18,-86.62,10.00,2,1,0
2,3,2021-02-01,35011,1037,32.90,-86.01,4.00,11,0,0
3,4,2021-02-01,35442,10107,33.18,-88.19,78.00,0,0,0
4,5,2021-02-01,35034,1007,32.92,-87.16,164.00,59,3,0
...,...,...,...,...,...,...,...,...,...,...
1502,1973,2021-02-01,0,0,35.86,-86.35,0.00,61,0,0
1503,1974,2021-02-01,0,0,38.65,-80.62,0.00,0,0,0
1504,1975,2021-02-01,0,0,32.98,-115.53,9.00,0,1,0
1505,1976,2021-02-01,0,0,40.86,-73.90,2.00,0,1,0
1506,1977,2021-02-01,0,0,0.00,0.00,233.00,174,1,2

In [7]:
listed.to_csv('jailed.csv', index=False)

In [8]:
jailed2

,Facility.ID,jurisdiction,State,Name,Address,City,Zipcode,County,County.FIPS,Latitude,Longitude,Residents.Confirmed,Staff.Confirmed,Residents.Deaths,Staff.Deaths,Date
1,1,state,Alabama,ALABAMA HEADQUARTERS,NaN,NaN,0,NaN,0,0.00,0.00,0.00,66,0,0,2021-02-01
2,2,state,Alabama,ALABAMA TREATMENT AND EDUCATION FACILITY,102 Industrial Parkway,Columbiana,35051,Shelby,1117,33.18,-86.62,10.00,2,1,0,2021-02-01
3,3,state,Alabama,ALEX CITY COMMUNITY BASED FACILITY,Highway 22 West,Alex City,35011,Coosa,1037,32.90,-86.01,4.00,11,0,0,2021-02-01
4,4,federal,Alabama,ALICEVILLE FEDERAL CORRECTIONAL INSTITUTION,11070 Highway 14,Aliceville,35442,Pickens,10107,33.18,-88.19,78.00,0,0,0,2021-02-01
5,5,state,Alabama,BIBB CORRECTIONAL FACILITY,565 Bibb Lane,Brent,35034,Bibb,1007,32.92,-87.16,164.00,59,3,0,2021-02-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1176,1973,state,Tennessee,DCCO AND OFFICE OF INVESTIGATIONS AND COMPLIANCE,NaN,NaN,0,NaN,0,35.86,-86.35,0.00,61,0,0,2021-02-01
1495,1974,state,West Virginia,CHARLESTON COMMUNITY CORRECTIONS,NaN,NaN,0,NaN,0,38.65,-80.62,0.00,0,0,0,2021-02-01
74,1975,federal,California,BRAWLEY RRC,NaN,Brawley,0,NaN,0,32.98,-115.53,9.00,0,1,0,2021-02-01
818,1976,federal,New York,GEO CARE RRC BRONX,NaN,Bronx,0,NaN,0,40.86,-73.90,2.00,0,1,0,2021-02-01
221,1977,state,District of Columbia,STATEWIDE,NaN,NaN,0,NaN,0,0.00,0.00,233.00,174,1,2,2021-02-01

In [9]:
jailed.to_csv('all.csv', index=False)