In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
pd.options.display.float_format = '{:.2f}'.format

In [2]:
race_df = pd.read_csv('https://raw.githubusercontent.com/datadesk/california-coronavirus-data/master/cdph-race-ethnicity.csv')
race_df

,date,race,age,confirmed_cases_total,confirmed_cases_percent,deaths_total,deaths_percent,population_percent
0,2021-10-20,asian,0-17,30300,0.05,4,0.11,0.13
1,2021-10-20,asian,18+,245821,0.08,8412,0.12,0.17
2,2021-10-20,asian,18-34,85035,0.07,95,0.08,0.15
3,2021-10-20,asian,35-49,60529,0.07,264,0.06,0.18
4,2021-10-20,asian,50-64,55812,0.08,1226,0.08,0.17
...,...,...,...,...,...,...,...,...
10459,2020-05-14,white,35-49,2392,0.18,11,0.08,0.33
10460,2020-05-14,white,50-64,3062,0.24,96,0.22,0.43
10461,2020-05-14,white,65-79,2433,0.36,312,0.34,0.54
10462,2020-05-14,white,80+,1665,0.44,569,0.42,0.57
10463,2020-05-14,white,all,11956,0.23,991,0.34,0.37

In [3]:
race_df.replace(to_replace =["other", "cdph-other"], value ="Other", inplace=True)
race_df.replace(to_replace ="asian", value ="Asian", inplace=True)
race_df.replace(to_replace ="black", value ="Black", inplace=True)
race_df.replace(to_replace ="latino", value ="Latino", inplace=True)
race_df.replace(to_replace ="white", value ="White", inplace=True)
race_df.replace(to_replace ="all", value ="Total", inplace=True)
race_df

,date,race,age,confirmed_cases_total,confirmed_cases_percent,deaths_total,deaths_percent,population_percent
0,2021-10-20,Asian,0-17,30300,0.05,4,0.11,0.13
1,2021-10-20,Asian,18+,245821,0.08,8412,0.12,0.17
2,2021-10-20,Asian,18-34,85035,0.07,95,0.08,0.15
3,2021-10-20,Asian,35-49,60529,0.07,264,0.06,0.18
4,2021-10-20,Asian,50-64,55812,0.08,1226,0.08,0.17
...,...,...,...,...,...,...,...,...
10459,2020-05-14,White,35-49,2392,0.18,11,0.08,0.33
10460,2020-05-14,White,50-64,3062,0.24,96,0.22,0.43
10461,2020-05-14,White,65-79,2433,0.36,312,0.34,0.54
10462,2020-05-14,White,80+,1665,0.44,569,0.42,0.57
10463,2020-05-14,White,Total,11956,0.23,991,0.34,0.37

In [4]:
race_df[race_df.age != '18+']

,date,race,age,confirmed_cases_total,confirmed_cases_percent,deaths_total,deaths_percent,population_percent
0,2021-10-20,Asian,0-17,30300,0.05,4,0.11,0.13
2,2021-10-20,Asian,18-34,85035,0.07,95,0.08,0.15
3,2021-10-20,Asian,35-49,60529,0.07,264,0.06,0.18
4,2021-10-20,Asian,50-64,55812,0.08,1226,0.08,0.17
5,2021-10-20,Asian,65-79,27348,0.10,2705,0.11,0.17
...,...,...,...,...,...,...,...,...
10459,2020-05-14,White,35-49,2392,0.18,11,0.08,0.33
10460,2020-05-14,White,50-64,3062,0.24,96,0.22,0.43
10461,2020-05-14,White,65-79,2433,0.36,312,0.34,0.54
10462,2020-05-14,White,80+,1665,0.44,569,0.42,0.57
10463,2020-05-14,White,Total,11956,0.23,991,0.34,0.37

In [5]:
g = race_df.groupby(['date', 'race', 'age'])['confirmed_cases_total', 'confirmed_cases_percent', 'deaths_total', 'deaths_percent', 'population_percent'].sum().reset_index()
g

<ipython-input-5-b6d144f4f56f>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  g = race_df.groupby(['date', 'race', 'age'])['confirmed_cases_total', 'confirmed_cases_percent', 'deaths_total', 'deaths_percent', 'population_percent'].sum().reset_index()

,date,race,age,confirmed_cases_total,confirmed_cases_percent,deaths_total,deaths_percent,population_percent
0,2020-05-14,Asian,0-17,80,0.04,0,0.00,0.13
1,2020-05-14,Asian,18-34,1177,0.09,3,0.11,0.15
2,2020-05-14,Asian,35-49,1498,0.12,11,0.08,0.18
3,2020-05-14,Asian,50-64,1627,0.13,53,0.12,0.17
4,2020-05-14,Asian,65-79,873,0.13,117,0.13,0.17
...,...,...,...,...,...,...,...,...
8715,2021-10-20,White,35-49,183013,0.21,542,0.13,0.33
8716,2021-10-20,White,50-64,184895,0.27,2840,0.20,0.43
8717,2021-10-20,White,65-79,106240,0.37,7231,0.30,0.54
8718,2021-10-20,White,80+,48341,0.47,11669,0.45,0.57
8719,2021-10-20,White,Total,857877,0.23,22421,0.32,0.37

In [6]:
g.to_csv('races.csv', index=False)