In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
pd.options.display.float_format = '{:.0f}'.format

In [2]:
scot_shot = pd.read_csv('https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/country_data/Scotland.csv')
scot_shot.tail()

,location,date,vaccine,source_url,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters
304,Scotland,2021-10-09,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",https://coronavirus.data.gov.uk/details/vaccin...,8115664,4253765,3861899,nan
305,Scotland,2021-10-10,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",https://coronavirus.data.gov.uk/details/vaccin...,8125794,4261124,3864670,nan
306,Scotland,2021-10-11,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",https://coronavirus.data.gov.uk/details/vaccin...,8132127,4265755,3866372,nan
307,Scotland,2021-10-12,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",https://coronavirus.data.gov.uk/details/vaccin...,8138782,4270126,3868656,nan
308,Scotland,2021-10-13,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",https://coronavirus.data.gov.uk/details/vaccin...,8146614,4275208,3871406,nan

In [3]:
scot_vac = scot_shot[['date', 'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated', 'location']]
scot_vac.rename(columns={'location' : 'country'}, inplace=True)
scot_vac.tail()

C:\Users\Doug Smith\anaconda3\lib\site-packages\pandas\core\frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,country
304,2021-10-09,8115664,4253765,3861899,Scotland
305,2021-10-10,8125794,4261124,3864670,Scotland
306,2021-10-11,8132127,4265755,3866372,Scotland
307,2021-10-12,8138782,4270126,3868656,Scotland
308,2021-10-13,8146614,4275208,3871406,Scotland

In [4]:
scot_vac.to_csv('scot_shot.csv', index=False)