In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
pd.options.display.float_format = '{:.3f}'.format

In [2]:
shots_df = pd.read_csv('covid19_vaccinations.csv')
shots_df

,State/Territory/Federal Entity,Total Doses Distributed,Doses Distributed per 100K,18+ Doses Distributed per 100K,Total Doses Administered by State where Administered,Doses Administered per 100k by State where Administered,18+ Doses Administered by State where Administered,18+ Doses Administered per 100K by State where Administered,People with at least One Dose by State of Residence,Percent of Total Pop with at least One Dose by State of Residence,...,People with a Second Booster Dose,People 50+ with a Second Booster Dose,Percent of People 50+ with First Booster Dose who Received Second Booster Dose,People 65+ with a Second Booster Dose,Percent of People 65+ with First Booster Dose who Received Second Booster Dose,People with Pfizer Second Booster Dose,People with Moderna Second Booster Dose,People with Janssen Second Booster Dose,People with Second Booster Dose of Other Manufacturer,Date
0,Alaska,1721465,235319,312107,1193878,163200,1064124,192929,520599,71.200,...,nan,38932,32.600,23911,39.400,19472,22049,54,14,8/3/2022
1,Alabama,10488440,213911,274935,6509742,132766,6063496,158943,3123070,63.700,...,nan,156452,22.300,113248,26.500,75216,89120,263,13,8/3/2022
2,Arkansas,6854480,227135,295751,4423901,146593,4030088,173887,2048912,67.900,...,nan,136025,28.800,99306,34.700,65961,75828,81,89,8/3/2022
3,Arizona,16175120,222225,286870,12824074,176186,11502180,203994,5459630,75.000,...,nan,417088,32.700,291826,38.900,244601,196562,597,1270,8/3/2022
4,California,98314885,248821,321106,79117100,200234,70244878,229427,33072578,83.700,...,nan,3093002,37.400,1903110,45.400,1646032,1673110,2243,54,8/3/2022
5,Colorado,13798775,239615,306693,11341872,196951,10182956,226327,4662052,81.000,...,nan,501694,42.100,318242,50.800,296032,239147,369,448,8/3/2022
6,Connecticut,9566125,268313,337091,7979336,223806,7145286,251785,3478917,95.000,...,nan,313950,34.500,210496,44.700,176386,148382,101,5,8/3/2022
7,District of Columbia,2100305,297599,363638,1644188,232971,1509811,261402,732152,95.000,...,nan,41044,36.000,25002,41.900,24581,23803,51,47,8/3/2022
8,Delaware,2598555,266857,337391,1911044,196253,1735895,225385,826375,84.900,...,nan,75570,33.900,54803,41.400,41526,36618,81,11,8/3/2022
9,Florida,52029985,242251,301661,39035508,181749,36203674,209903,17312019,80.600,...,nan,1260797,29.000,920552,34.600,657146,661693,1932,3661,8/3/2022
10,Georgia,23761555,223798,292863,15496475,145953,14131114,174167,7057617,66.500,...,nan,344074,23.100,224116,28.100,180879,186980,347,433,8/3/2022
11,Hawaii,3774880,266612,338250,3132647,221252,2800740,250961,1262838,89.200,...,nan,161079,43.000,105944,51.200,86450,82640,120,11,8/3/2022
12,Iowa,7337855,232573,302190,5357159,169795,4885829,201210,2172629,68.900,...,nan,244929,34.600,179990,43.100,131094,120800,91,9,8/3/2022
13,Idaho,3810690,213237,284621,2566632,143623,2349930,175517,1110935,62.200,...,nan,89825,30.600,65737,36.800,50929,42428,86,34,8/3/2022
14,Illinois,30030375,236985,304755,23644004,186587,21055710,213678,9748453,76.900,...,nan,954187,34.900,629093,43.000,565125,449890,1033,1085,8/3/2022
15,Indiana,14832680,220324,287219,10217358,151768,9329906,180664,4236736,62.900,...,nan,314686,26.300,225376,32.500,194097,138177,406,804,8/3/2022
16,Kansas,6714715,230484,303413,4759954,163386,4274406,193144,2149192,73.800,...,nan,167181,31.500,121329,38.800,94756,78557,171,90,8/3/2022
17,Kentucky,9771575,218717,282024,6796916,152135,6245162,180246,3000794,67.200,...,nan,218628,27.400,153587,33.500,124984,102628,265,26,8/3/2022
18,Louisiana,8927950,192049,250703,6490846,139624,6011787,168815,2874375,61.800,...,nan,172409,23.600,122667,28.400,99685,82271,154,9,8/3/2022
19,Massachusetts,18454170,267743,333126,15643667,226966,13963850,252069,6945801,95.000,...,nan,562527,34.700,364263,43.500,297965,295012,241,7,8/3/2022
20,Maryland,17558570,290432,372715,12814246,211957,11342726,240771,5343786,88.400,...,nan,579073,40.800,364244,50.400,321458,297427,723,710,8/3/2022
21,Maine,3790050,281953,346006,3023515,224928,2761750,252129,1246777,92.800,...,nan,166559,40.800,117196,50.300,86929,83794,94,173,8/3/2022
22,Michigan,23431010,234618,298754,16476735,164984,15093484,192447,6760202,67.700,...,nan,644547,29.800,455223,37.200,351997,317095,435,29,8/3/2022
23,Minnesota,14067860,249446,324408,10943083,194039,9756970,224998,4305859,76.300,...,nan,583881,42.500,393388,52.100,352941,254683,289,136,8/3/2022
24,Missouri,12699405,206917,266411,9369450,152661,8578574,179963,4130915,67.300,...,nan,312856,30.300,226612,36.600,181975,143002,160,12,8/3/2022
25,Mississippi,6075415,204137,266750,4030850,135438,3724163,163515,1803879,60.600,...,nan,105383,23.300,74867,27.900,53478,57909,114,243,8/3/2022
26,Montana,2180495,204018,259524,1658980,155222,1528195,181887,707642,66.200,...,nan,62591,30.400,47085,36.500,34606,30627,107,72,8/3/2022
27,North Carolina,24244920,231166,296126,17507850,166931,15885190,194021,9096567,86.700,...,nan,267265,22.300,179673,26.500,140454,139513,163,10,8/3/2022
28,North Dakota,1520700,199551,261338,1147606,150592,1046981,179927,508168,66.700,...,nan,24454,19.800,17626,23.700,14266,11303,5,8,8/3/2022
29,Nebraska,4390940,226991,301093,3361937,173797,3016830,206868,1381210,71.400,...,nan,131685,33.200,92100,40.300,84919,52880,100,237,8/3/2022
30,New Hampshire,3917600,288120,354708,2697251,198369,2456590,222425,1226307,90.200,...,nan,86202,28.600,57971,36.300,49209,39675,71,33,8/3/2022
31,New Jersey,24015715,270381,345868,17969587,202310,16094653,231791,8172158,92.000,...,nan,543676,28.300,355776,36.500,298391,275979,778,36,8/3/2022
32,New Mexico,4877645,232620,300905,4154441,198130,3720549,229523,1884615,89.900,...,nan,182245,39.300,121792,47.300,103145,88554,247,143,8/3/2022
33,Nevada,6463110,209831,270704,5100859,165604,4660547,195205,2361265,76.700,...,nan,146937,30.000,102130,37.100,83973,68740,48,5,8/3/2022
34,New York,49730495,255637,322396,40801475,209738,36936731,239456,17831599,91.700,...,nan,1137325,27.900,774234,36.500,620199,579072,1724,169,8/3/2022
35,Ohio,25378555,217113,278546,18674081,159756,17114941,187848,7499881,64.200,...,nan,766629,31.600,539478,38.500,437239,363116,900,414,8/3/2022
36,Oklahoma,7976760,201588,265473,6147940,155370,5641587,187757,2863385,72.400,...,nan,152665,25.200,112004,31.000,79793,79642,125,520,8/3/2022
37,Oregon,11119085,263627,331797,8211432,194688,7434308,221842,3333542,79.000,...,nan,404712,42.800,277942,50.300,229318,195326,317,104,8/3/2022
38,Pennsylvania,33691885,263177,331372,24259254,189496,22046584,216837,11144803,87.100,...,nan,765806,29.300,545825,35.900,407918,394570,386,18,8/3/2022
39,Rhode Island,2824725,266644,330429,2332401,220171,2112572,247123,1072278,95.000,...,nan,94931,32.700,63595,41.700,54142,47148,147,40,8/3/2022
40,South Carolina,11583775,224984,286902,7864789,152752,7255235,179695,3550978,69.000,...,nan,227830,25.500,168244,30.700,128793,108156,216,24,8/3/2022
41,South Dakota,2088765,236110,312896,1493218,168790,1348066,201940,695116,78.600,...,nan,49838,30.700,36911,37.600,28361,23073,26,2,8/3/2022
42,Tennessee,14081930,206203,264742,10377508,151958,9648123,181386,4307881,63.100,...,nan,341348,29.300,240792,35.100,194686,166895,669,2890,8/3/2022
43,Texas,67218465,231821,311253,47753595,164691,41905146,194041,21439828,73.900,...,nan,1078450,27.500,694304,33.800,584154,579625,353,52,8/3/2022
44,Utah,6851750,213719,301206,5442431,169760,4711195,207106,2349022,73.300,...,nan,132242,26.900,86849,32.900,89982,55195,327,2,8/3/2022
45,Virginia,21519385,252116,322404,17252267,202123,15335820,229761,7467043,87.500,...,nan,629968,34.400,409418,42.100,362865,310944,748,295,8/3/2022
46,Vermont,1983090,317808,388853,1490952,238939,1333062,261393,595935,95.000,...,nan,72118,37.200,50276,46.800,40619,34679,53,1,8/3/2022
47,Washington,19661495,258198,330344,15260662,200405,13684259,229917,6276147,82.400,...,nan,705290,42.100,460987,50.500,393456,354837,654,331,8/3/2022
48,Wisconsin,12783445,219555,280595,10824589,185912,9851685,216243,4244857,72.900,...,nan,535043,37.800,379299,46.800,306532,246108,215,44,8/3/2022
49,West Virginia,4475845,249748,312432,2837891,158351,2653254,185208,1181990,66.000,...,nan,97183,27.600,70588,32.800,53214,48375,62,32,8/3/2022
50,Wyoming,1070885,185031,240635,772940,133551,716671,161041,341423,59.000,...,nan,25820,27.700,19498,33.200,13464,13336,18,14,8/3/2022

In [3]:
shots_df['Pop'] = shots_df['Total Doses Distributed']/(shots_df['Doses Distributed per 100K']/100000)
shots_df.head()

,State/Territory/Federal Entity,Total Doses Distributed,Doses Distributed per 100K,18+ Doses Distributed per 100K,Total Doses Administered by State where Administered,Doses Administered per 100k by State where Administered,18+ Doses Administered by State where Administered,18+ Doses Administered per 100K by State where Administered,People with at least One Dose by State of Residence,Percent of Total Pop with at least One Dose by State of Residence,...,People 50+ with a Second Booster Dose,Percent of People 50+ with First Booster Dose who Received Second Booster Dose,People 65+ with a Second Booster Dose,Percent of People 65+ with First Booster Dose who Received Second Booster Dose,People with Pfizer Second Booster Dose,People with Moderna Second Booster Dose,People with Janssen Second Booster Dose,People with Second Booster Dose of Other Manufacturer,Date,Pop
0,Alaska,1721465,235319,312107,1193878,163200,1064124,192929,520599,71.200,...,38932,32.600,23911,39.400,19472,22049,54,14,8/3/2022,731545.264
1,Alabama,10488440,213911,274935,6509742,132766,6063496,158943,3123070,63.700,...,156452,22.300,113248,26.500,75216,89120,263,13,8/3/2022,4903179.360
2,Arkansas,6854480,227135,295751,4423901,146593,4030088,173887,2048912,67.900,...,136025,28.800,99306,34.700,65961,75828,81,89,8/3/2022,3017799.987
3,Arizona,16175120,222225,286870,12824074,176186,11502180,203994,5459630,75.000,...,417088,32.700,291826,38.900,244601,196562,597,1270,8/3/2022,7278713.016
4,California,98314885,248821,321106,79117100,200234,70244878,229427,33072578,83.700,...,3093002,37.400,1903110,45.400,1646032,1673110,2243,54,8/3/2022,39512293.978

In [4]:
booster_df = shots_df[['State/Territory/Federal Entity', 'Total Doses Distributed', 'Doses Distributed per 100K', 'People with a first booster dose','Percent of fully vaccinated people with a first booster dose' ,'Pop', 'Date' ]]
booster_df.head()

,State/Territory/Federal Entity,Total Doses Distributed,Doses Distributed per 100K,People with a first booster dose,Percent of fully vaccinated people with a first booster dose,Pop,Date
0,Alaska,1721465,235319,215249,46.700,731545.264,8/3/2022
1,Alabama,10488440,213911,956725,37.600,4903179.360,8/3/2022
2,Arkansas,6854480,227135,695429,41.600,3017799.987,8/3/2022
3,Arizona,16175120,222225,2043195,44.700,7278713.016,8/3/2022
4,California,98314885,248821,16025223,55.400,39512293.978,8/3/2022

In [5]:
#booster_df['Booster Percent'] = booster_df['People with a first booster dose']/(booster_df['Pop'])
booster_df.head()

,State/Territory/Federal Entity,Total Doses Distributed,Doses Distributed per 100K,People with a first booster dose,Percent of fully vaccinated people with a first booster dose,Pop,Date
0,Alaska,1721465,235319,215249,46.700,731545.264,8/3/2022
1,Alabama,10488440,213911,956725,37.600,4903179.360,8/3/2022
2,Arkansas,6854480,227135,695429,41.600,3017799.987,8/3/2022
3,Arizona,16175120,222225,2043195,44.700,7278713.016,8/3/2022
4,California,98314885,248821,16025223,55.400,39512293.978,8/3/2022

In [6]:
booster_df = booster_df.rename(columns = {'State/Territory/Federal Entity' : 'State', 'Total Doses Distributed' : 'Total Doses', 'Doses Distributed per 100K' : 'Doses per 100K', 'People who have received a booster dose' : 'Booster Doses'})
booster_df.head()

,State,Total Doses,Doses per 100K,People with a first booster dose,Percent of fully vaccinated people with a first booster dose,Pop,Date
0,Alaska,1721465,235319,215249,46.700,731545.264,8/3/2022
1,Alabama,10488440,213911,956725,37.600,4903179.360,8/3/2022
2,Arkansas,6854480,227135,695429,41.600,3017799.987,8/3/2022
3,Arizona,16175120,222225,2043195,44.700,7278713.016,8/3/2022
4,California,98314885,248821,16025223,55.400,39512293.978,8/3/2022

In [7]:
# Export updated national data to csv for use in Tableau

booster_df.to_csv('booster.csv', index=False)