In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
pd.options.display.float_format = '{:.3f}'.format

In [2]:
shots_df = pd.read_csv('covid19_vaccinations.csv')
shots_df

,State/Territory/Federal Entity,Total Doses Delivered,Doses Delivered per 100K,18+ Doses Delivered per 100K,Total Doses Administered by State where Administered,Doses Administered per 100k by State where Administered,18+ Doses Administered by State where Administered,18+ Doses Administered per 100K by State where Administered,People with at least One Dose by State of Residence,Percent of Total Pop with at least One Dose by State of Residence,...,Percent People Primary Moderna Booster Other,Percent People Primary J&J Booster Pfizer,Percent People Primary J&J Booster Moderna,Percent People Primary J&J Booster J&J,Percent People Primary J&J Booster Other,Percent People Primary Other Booster Pfizer,Percent People Primary Other Booster Moderna,Percent People Primary Other Booster J&J,Percent People Primary Other Booster Uknown,Date
0,Alaska,1482265,202621,268740,1113386,152197,998300,180995,506076,69.200,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
1,Alabama,9396740,191646,246318,6154128,125513,5744279,150576,3051334,62.200,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
2,Arkansas,5952680,197252,256841,4131074,136890,3767302,162548,1995676,66.100,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
3,Arizona,14312020,196628,253828,11746475,161381,10573581,187525,5255628,72.200,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
4,California,87229285,220765,284899,72551454,183618,64649062,211150,32584419,82.500,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
5,Colorado,12046675,209190,267750,10429779,181112,9394383,208800,4537175,78.800,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
6,Connecticut,8439225,236705,297381,7377585,206928,6614314,233075,3370009,94.500,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
7,District of Columbia,1806005,255899,312684,1455412,206222,1355480,234682,681969,95.000,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
8,Delaware,2264955,232598,294077,1753053,180029,1594269,206996,801440,82.300,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
9,Florida,46351885,215814,268741,36501765,169952,33890861,196494,16876190,78.600,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
10,Georgia,21002095,197808,258852,14538339,136929,13290355,163805,6881039,64.800,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
11,Hawaii,3350880,236665,300257,2836263,200319,2540776,227667,1230710,86.900,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
12,Iowa,6347955,201199,261423,4966812,157423,4536698,186832,2132046,67.600,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
13,Idaho,3273690,183188,244513,2392761,133893,2190968,163644,1084538,60.700,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
14,Illinois,26536245,209411,269296,22036308,173900,19659619,199510,9678523,76.400,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
15,Indiana,12882680,191359,249459,9306089,138232,8532296,165219,4109748,61.000,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
16,Kansas,5827515,200030,263323,4496448,154341,4054312,183199,2155078,74.000,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
17,Kentucky,8565075,191712,247202,6393211,143099,5882652,169783,2937384,65.700,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
18,Louisiana,8014850,172407,225063,6138818,132052,5697320,159985,2819786,60.700,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
19,Massachusetts,16417010,238186,296352,14417064,209170,12914356,233124,6692123,95.000,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
20,Maryland,15271770,252606,324173,11676871,193144,10378753,220309,5174680,85.600,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
21,Maine,3244850,241394,296233,2728073,202950,2490871,227400,1201971,89.400,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
22,Michigan,20369810,203966,259722,15446970,154673,14154450,180474,6649945,66.600,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
23,Minnesota,12124430,214986,279592,10004774,177401,8933509,206009,4211363,74.700,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
24,Missouri,11226605,182920,235514,8740962,142421,8021053,168268,4034552,65.700,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
25,Mississippi,5381215,180811,236270,3802845,127777,3519874,154545,1761847,59.200,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
26,Montana,1908595,178577,227162,1549802,145007,1428483,170019,692802,64.800,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
27,North Carolina,21224500,202368,259235,16305336,155465,14833053,181170,8705591,83.000,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
28,North Dakota,1329400,174448,228462,1067243,140047,980365,168479,492552,64.600,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
29,Nebraska,3828310,197906,262513,3109070,160725,2801132,192078,1348019,69.700,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
30,New Hampshire,3358030,246966,304043,2355040,173202,2146912,194386,1198601,88.200,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
31,New Jersey,21300955,239816,306771,16768564,188789,15048649,216727,7962196,89.600,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
32,New Mexico,4304545,205288,265550,3818694,182118,3422753,211152,1817777,86.700,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
33,Nevada,5762110,187072,241343,4783305,155294,4376406,183304,2296914,74.600,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
34,New York,44651045,229526,289467,38274701,196749,34743466,225237,17413422,89.500,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
35,Ohio,22327755,191013,245062,17394414,148809,15977358,175362,7387919,63.200,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
36,Oklahoma,7074130,178776,235433,5780216,146077,5313184,176827,2787588,70.400,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
37,Oregon,9669285,229253,288534,7526561,178450,6821414,203553,3263487,77.400,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
38,Pennsylvania,29338425,229171,288555,22334165,174459,20367870,200326,10746758,83.900,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
39,Rhode Island,2518825,237768,294646,2155846,203504,1954468,228629,1030809,95.000,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
40,South Carolina,10144575,197031,251257,7357447,142899,6802570,168483,3452386,67.100,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
41,South Dakota,1796365,203057,269095,1370811,154954,1241089,185915,667872,75.500,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
42,Tennessee,12458530,182431,234222,9701693,142062,9040223,169957,4212371,61.700,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
43,Texas,59869535,206476,277224,45140170,155678,39879030,184659,20872865,72.000,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
44,Utah,6082950,189739,267409,5116903,159606,4448910,195576,2294733,71.600,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
45,Virginia,19043485,223109,285310,16051306,188053,14309741,214389,7251725,85.000,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
46,Vermont,1725050,276455,338256,1359084,217806,1218245,238879,578835,92.800,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
47,Washington,17150495,225223,288155,14025225,184182,12633615,212264,6109548,80.200,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
48,Wisconsin,11208545,192506,246026,9969775,171230,9084415,199402,4157567,71.400,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
49,West Virginia,3919945,218729,273628,2657731,148299,2485259,173481,1156637,64.500,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022
50,Wyoming,946785,163589,212749,737957,127507,683461,153578,337651,58.300,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022

In [3]:
shots_df['Pop'] = shots_df['Total Doses Delivered']/(shots_df['Doses Delivered per 100K']/100000)
shots_df.head()

,State/Territory/Federal Entity,Total Doses Delivered,Doses Delivered per 100K,18+ Doses Delivered per 100K,Total Doses Administered by State where Administered,Doses Administered per 100k by State where Administered,18+ Doses Administered by State where Administered,18+ Doses Administered per 100K by State where Administered,People with at least One Dose by State of Residence,Percent of Total Pop with at least One Dose by State of Residence,...,Percent People Primary J&J Booster Pfizer,Percent People Primary J&J Booster Moderna,Percent People Primary J&J Booster J&J,Percent People Primary J&J Booster Other,Percent People Primary Other Booster Pfizer,Percent People Primary Other Booster Moderna,Percent People Primary Other Booster J&J,Percent People Primary Other Booster Uknown,Date,Pop
0,Alaska,1482265,202621,268740,1113386,152197,998300,180995,506076,69.200,...,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022,731545.595
1,Alabama,9396740,191646,246318,6154128,125513,5744279,150576,3051334,62.200,...,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022,4903175.647
2,Arkansas,5952680,197252,256841,4131074,136890,3767302,162548,1995676,66.100,...,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022,3017804.636
3,Arizona,14312020,196628,253828,11746475,161381,10573581,187525,5255628,72.200,...,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022,7278729.377
4,California,87229285,220765,284899,72551454,183618,64649062,211150,32584419,82.500,...,nan,nan,nan,nan,nan,nan,nan,nan,3/27/2022,39512280.026

In [4]:
booster_df = shots_df[['State/Territory/Federal Entity', 'Total Doses Delivered', 'Doses Delivered per 100K', 'People who have received a booster dose', 'Pop', 'Date' ]]
booster_df.head()

,State/Territory/Federal Entity,Total Doses Delivered,Doses Delivered per 100K,People who have received a booster dose,Pop,Date
0,Alaska,1482265,202621,190024,731545.595,3/27/2022
1,Alabama,9396740,191646,864594,4903175.647,3/27/2022
2,Arkansas,5952680,197252,627762,3017804.636,3/27/2022
3,Arizona,14312020,196628,1797292,7278729.377,3/27/2022
4,California,87229285,220765,13890035,39512280.026,3/27/2022

In [5]:
booster_df['Booster Percent'] = booster_df['People who have received a booster dose']/(booster_df['Pop'])
booster_df.head()

<ipython-input-5-b5e0594bff54>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  booster_df['Booster Percent'] = booster_df['People who have received a booster dose']/(booster_df['Pop'])

,State/Territory/Federal Entity,Total Doses Delivered,Doses Delivered per 100K,People who have received a booster dose,Pop,Date,Booster Percent
0,Alaska,1482265,202621,190024,731545.595,3/27/2022,0.260
1,Alabama,9396740,191646,864594,4903175.647,3/27/2022,0.176
2,Arkansas,5952680,197252,627762,3017804.636,3/27/2022,0.208
3,Arizona,14312020,196628,1797292,7278729.377,3/27/2022,0.247
4,California,87229285,220765,13890035,39512280.026,3/27/2022,0.352

In [6]:
booster_df = booster_df.rename(columns = {'State/Territory/Federal Entity' : 'State', 'Total Doses Delivered' : 'Total Doses', 'Doses Delivered per 100K' : 'Doses per 100K', 'People who have received a booster dose' : 'Booster Doses'})
booster_df.head()

,State,Total Doses,Doses per 100K,Booster Doses,Pop,Date,Booster Percent
0,Alaska,1482265,202621,190024,731545.595,3/27/2022,0.260
1,Alabama,9396740,191646,864594,4903175.647,3/27/2022,0.176
2,Arkansas,5952680,197252,627762,3017804.636,3/27/2022,0.208
3,Arizona,14312020,196628,1797292,7278729.377,3/27/2022,0.247
4,California,87229285,220765,13890035,39512280.026,3/27/2022,0.352

In [7]:
# Export updated national data to csv for use in Tableau

booster_df.to_csv('booster.csv', index=False)