In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
pd.options.display.float_format = '{:.0f}'.format

In [2]:
us_shot = pd.read_csv('https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/country_data/United%20States.csv')
us_shot.tail()

,location,date,vaccine,source_url,total_vaccinations,people_vaccinated,people_fully_vaccinated
92,United States,2021-04-05,"Johnson&Johnson, Moderna, Pfizer/BioNTech",https://covid.cdc.gov/covid-data-tracker/#vacc...,167187795,107515428,62392065
93,United States,2021-04-06,"Johnson&Johnson, Moderna, Pfizer/BioNTech",https://covid.cdc.gov/covid-data-tracker/#vacc...,168592075,108301234,63016976
94,United States,2021-04-07,"Johnson&Johnson, Moderna, Pfizer/BioNTech",https://covid.cdc.gov/covid-data-tracker/#vacc...,171476655,109995734,64422618
95,United States,2021-04-08,"Johnson&Johnson, Moderna, Pfizer/BioNTech",https://covid.cdc.gov/covid-data-tracker/#vacc...,174879716,112046611,66203123
96,United States,2021-04-09,"Johnson&Johnson, Moderna, Pfizer/BioNTech",https://covid.cdc.gov/covid-data-tracker/#vacc...,178837781,114436039,68202458

In [3]:
us_vac = us_shot[['date', 'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated', 'location']]
us_vac.rename(columns={'location' : 'country'}, inplace=True)
us_vac.tail()

C:\Users\Doug Smith\anaconda3\lib\site-packages\pandas\core\frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,country
92,2021-04-05,167187795,107515428,62392065,United States
93,2021-04-06,168592075,108301234,63016976,United States
94,2021-04-07,171476655,109995734,64422618,United States
95,2021-04-08,174879716,112046611,66203123,United States
96,2021-04-09,178837781,114436039,68202458,United States

In [4]:
us_vac.to_csv('us_shot.csv', index=False)